<a href="https://colab.research.google.com/github/ahmadhajmosa/Machine-learning-labs/blob/AnastasiiaSK/Copy_of_Session_1_working_version.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

test

In [0]:
print('hello world')

hello world


# Lab on Machine Learning and Applications in Intelligent Vehicles
## Session 1: Introduction


### Course Plan:

This lab is a continuation to the Machine learning lecture, the objective of this course is to learn how to model and implement neural networks using deep learning python frameworks: 
1. Tensorflow
2. Keras
3. Pytorch

Useing these frameworks, we will go through the following topics and use cases:

#### Session 1: 05.06 - 09:00 - 11:00  :

>#### Presentation:  05.06 - 09:00 - 10:30:
>1. Introduction to deep learning frameworks
2. Deep learning in Numpy

>#### Break:  05.06 - 10:30 - 10:45
>#### Assignment:  05.06 - 10:45 - 11:45 : 
>* Implementation of backprop using numpy

>1. Tensorflow backround 
2. Implementation of feedforward neural networks using Tensorflow

>#### Break:  05.06 - 10:00 - 10:15
>#### Assignment:  05.06 - 10:15 - 10:45 : 
  
  >* play around with tensorflow and build your first neural network



#### Session 2:  05.06 - 11:00 - 12:00  :

>#### Presentation:  05.06 - 11:00 - 12:00:


>3. Implementation of CNN useing Tensorflow
4. Tensorboard

>#### Break:  05.06 - 12:00 - 13:00
>#### Assignment:  05.06 - 13:00 - 13:30 :


 #### Session 3:  05.06 - 13:30 - 15:00  :

>#### Presentation:  05.06 - 13:00 - 14:00:

>5. Introduction to Keras
6. CNN using Keras
>#### Break:  05.06 - 14:00 - 14:15
>#### Assignment:  05.06 - 14:15 - 14:45 :

 #### Session 4:  05.06 - 15:00 - 16:30  :

>#### Presentation:  05.06 - 15:00 - 15:45:

>7. LSTM using Keras

>#### Break:  05.06 - 15:45 - 16:00
>#### Assignment:  05.06 - 16:00 - 16:30 :


8. VGG, Inceptaion, ResNet models using Keras

9. Autoencoders using Keras

10. Sequence to Sequence Models using Keras 

11. Attention Mechanism using Keras
12. GANS 
13. Introduction to Pytorch
14. Machine translation using Pytorch
15. Introduction to Allennlp
16. Deep Reinforcment Learning using Keras
17. Use case: building self driving car using Unity and tensorflow










# New Section

#Session 1: 05.06 - 09:00 - 11:00 :




## Deep learning frameworks:

In the past decade, many deep learning frameworks have been developed to ease and scale the research and development of AI. Many big technology providers including Google, IBM, Microsoft and Facebook have entered the race to provide the best and most popluar frameworks. To enter such a race, mainly four features are considered in the provided framework:

1. Uses a popular language for data scientists (Python, Scale, C++ or R)
2. Flexible in creating and adjusting deep learning architectures -> Functional programming
3. Easy for computing gradients
4. Interface with GPUs for parallel processing


In the following we see the most popular provided deep learning frameworks with their providers
https://towardsdatascience.com/deep-learning-framework-power-scores-2018-23607ddf297a

![alt text](https://cdn-images-1.medium.com/max/1600/1*dYjDEI0mLpsCOySKUuX1VA.png)

## Tensorflow
TensorFlow is the undisputed heavyweight champion. It has the most GitHub activity, Google searches, Medium articles, books on Amazon and ArXiv articles. It also has the most developers using it and is listed in the most online job descriptions. TensorFlow is backed by Google.

## Keras
Keras has an “API designed for human beings, not machines.” It is the second most popular framework in nearly all evaluation areas. Keras sits on top of TensorFlow, Theano, or CNTK. Start with Keras if you are new to deep learning.

## Pytorch

PyTorch is the third most popular overall framework and the second most popular stand-alone framework. It is younger than TensorFlow and has grown rapidly in popularity. It allows customization that TensorFlow does not. It has the backing of Facebook.

## Theano

Theano was developed at the University of Montreal in 2007 and is the oldest significant Python deep learning framework. It has lost much of its popularity and its leader stated that major releases were no longer on the roadmap. However, updates continue to be made. Theano still the fifth highest scoring framework.

# Comparision:

## Criteria 1: Online Job Listings

TensorFlow is the clear winner when it comes to frameworks mentioned in job listings. Learn it if you want a job doing deep learning.

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*kA8dIgRqLdWgKgs2sd7clA.png)

## Criteria 2: Usage


Keras showed a surprising amount of use — nearly as much as TensorFlow. It’s interesting that US employers are overwhelmingly looking for TensorFlow skills, when — at least internationally — Keras is used almost as frequently.

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*6b2Tm0oFr99zKaxkr4g52w.png)
  
  
## Criteria 4: Google Search Activity

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*wpA6C9x_Nri42EzbqnS1fQ.png)

## Criteria 5: Medium Articles

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*Y1cJUgZTC3u_hU1lmdsroQ.png)


## Criteria 6: Amazon Books

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*mtP47q29T6agdkEoJcCw-w.png)

## Criteria 7 : ArXiv Articles

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*7jdNoNkGlx_1EnfevQXRvw.png)
  
## Criteria 8: GitHub Activity

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*eOOYV3C5klsuVBMX31ngxw.png)
  
 --------------------------------
 


  
 






In [0]:
!pip install -q matplotlib-venn

In [0]:
!apt-get -qq install -y libfluidsynth1



```
# This is formatted as code
```


Before we jump into Tensorflow, we will implemented our first neural network model using Python Numpy package. NumPy is the fundamental package for scientific computing with Python, such as:

1. Linear Algebra
2. Statistics
3. Calculus

## A brief intro to Numpy operations:

1. Creating a Vector:
Here we use Numpy to create a 1-D Array which we then call a vector.





In [0]:
import numpy as np

v1 = np.zeros((1,100))
#display(v1) 

v2 = np.zeros((1,100))
#display(v2)
v2.T.shape
v3 = np.ones((1,100))
v4 = np.eye(4)
#display(v4)
v5 = np.random.randn(100,1) #normal random generator with mean 0 and 1 std
#display(v5)
v6 = np.random.rand(100,1)  #unifom random generator between 0 and 1
display('mean of randn:',v5.mean())
display('std of randn:',v5.std())
display('min of rand',v6.min())
display('max of rand',v6.max())


2. Creating a Matrix
We Create a 2-D Array in Numpy and call it a Matrix. It contains 2 rows and 3 columns.

In [0]:
m1 = np.zeros((2,3))
display(m1)

matrix = np.array([[1,2,3],[4,5,6]])
display('matrix:', matrix)
display('matrix shape:', matrix.shape)

array([[0., 0., 0.],
       [0., 0., 0.]])

'matrix:'

array([[1, 2, 3],
       [4, 5, 6]])

'matrix shape:'

(2, 3)

3. Selecting Elements


In [0]:

display(matrix[0]) #first row
display(matrix[0,0]) #first row first col
display(matrix[0,-1]) #first row last col
display(matrix[0,-2]) #first row second last col
display(matrix[0,1:]) #first row from second element
display(matrix[0,:-1]) #first row from first element to second last 
display(matrix[0,0:2]) #first row elements from 0 to 2
display(matrix[-1,0:2]) #last row from 0 tp 2

array([1, 2, 3])

1

3

2

array([2, 3])

array([1, 2])

array([1, 2])

array([4, 5])

4. Describing a Matrix

In [0]:
#View the Number of rows and columns
print(matrix.shape) 
#view the number of elements (rows*columns)
print(matrix.size)
#View the number of Dimensions(2 in this case)
print(matrix.ndim)

(2, 3)
6
2


5. Finding the max and min values

In [0]:
display(matrix)
matrix.min() #min in all matrix
display(matrix.min(axis=0))# min elementin the first row


display(np.min(matrix,axis=1))
display(np.max(matrix,axis=1))
display('arg: ',np.argmax(matrix,axis=0))
display('max: ',np.argmax(matrix,axis=0))# in the first row
display('max: ',np.argmax(matrix))
np.argwhere(matrix < np.max(matrix)) #values that smaller then max(indexes of them)

array([[1, 2, 3],
       [4, 5, 6]])

array([1, 2, 3])

array([1, 4])

array([3, 6])

'arg: '

array([1, 1, 1])

'max: '

array([1, 1, 1])

'max: '

5

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 1]])

6. Reshaping Arrays


In [0]:
matrix.shape
matrix.reshape((3,2))
matrix.reshape((6,1))
matrix.reshape(1,2,3) #dim 0 size = 1, dim 1= 2, dim 2=3
matrix.reshape(1,-1,3).shape #dim 0 size=1,dim 1=2,dim 2=3 -1:automatically calc

(1, 2, 3)

7. Calculating Dot Products

In [0]:
#create vectors
vector_1=np.array([1,2,3])
vector_2 = np.array([4,5,6])
#calculate dot product (summa umnozehiya elementa na element)
print(np.dot(vector_1,vector_2))
#alternatively you can use @ to calculate dot products
print(vector_1 @ vector_2)

32
32


##Linear regression in Numpy:

---



Write the numpy code for the following model:

$Y=WX+B$

where $X$ is 3x10 matrix:  10 samples and 3 features

$Y$ is 4x10 matrix: 10 samples and 4 outputs

$W$ is the weights matrix with the shape 4x3: connecting 3 inputs to 4 outputs

$b$ is a vector with a size 4 ( one bias per output)


In [0]:
#inuts or features matrix
X = np.random.rand(3,10)
display('shape of X', X.shape)

#weights matrix
W=np.random.rand(4,3)
#b = np.zeros(4,) vector with 4 elements

#bias 
b = np.zeros((4,1))

Y = np.dot(W,X)+b #4x3, 3x10
display('Y:', Y.shape)

'shape of X'

(3, 10)

'Y:'

(4, 10)

## One neuron model in numpy:

A single neuron has multiple inputs and one output, in addition to the linear regression model, we need to add non linearity through an activation function:

$Y= f(WX+B)$

where $X$ is n x m matrix:  m samples and n features/inputs

$f(g)= \frac{1}{1+\exp(-g)}$  is a sigmoid acitavation function

$Y$ is nh1 x m matrix: m samples and ny outputs

$W$ is the weights matrix with the shape nh1 x n: connecting 3 inputs to 4 outputs

$b$ is a vector with a size nh1 ( one bias per output)





In [0]:
num_inputs = 3
num_outputs = 4
num_samples = 100
f = lambda x: 1.0 /(1.0 + np.exp(-x)) #activation fuction(use sigmoid)
X = np.random.rand(num_inputs,num_samples)

# generate random weights vector
W=np.random.rand(num_outputs,num_inputs)

#bias 
b = np.zeros((num_outputs,1))
 #calculate Y
Y = f(np.dot(W,X)+b) 
display('Y:', Y)
display('Y shape:', Y.shape)
for i in range(2): 
  print('hi')

'Y:'

array([[0.78263564, 0.7628679 , 0.67156657, 0.76527556, 0.72631412,
        0.69564963, 0.77418319, 0.78407563, 0.80747433, 0.74974741,
        0.58973706, 0.74147522, 0.82706065, 0.63691149, 0.77361932,
        0.7490505 , 0.83594021, 0.71859113, 0.69428016, 0.81156337,
        0.6962344 , 0.84019281, 0.77866219, 0.70897903, 0.74808971,
        0.72550744, 0.85582204, 0.7539276 , 0.71752543, 0.6988643 ,
        0.64762663, 0.69947776, 0.69529975, 0.68365591, 0.72242886,
        0.74243547, 0.80204805, 0.67605606, 0.78151672, 0.60447989,
        0.65273718, 0.72816754, 0.76732752, 0.71356688, 0.77377768,
        0.73737135, 0.63906181, 0.70779049, 0.64162933, 0.82909632,
        0.82503283, 0.66537291, 0.67056568, 0.60726937, 0.82062476,
        0.68170643, 0.60335528, 0.71503692, 0.6400717 , 0.76849772,
        0.77168219, 0.67704719, 0.7833318 , 0.65163562, 0.57859663,
        0.70912788, 0.64458582, 0.71497632, 0.82452723, 0.66046099,
        0.78711   , 0.765376  , 0.69582176, 0.71

'Y shape:'

(4, 100)

hi
hi


## Two hidden layer model in numpy:

The difference from the one neuron model is simple:  we need only to change the number of output "ny"

In [0]:
num_inputs = 3
hidden_layer_1_outputs = 4
hidden_layer_2_outputs = 3
num_samples = 100
X = np.random.rand(num_inputs,num_samples)

# generate random weights vector for the first hidden layer
W_h1=np.random.rand(hidden_layer_1_outputs ,num_inputs)

# generate random weights vector for the second hidden layer
W_h2=np.random.rand(hidden_layer_2_outputs ,hidden_layer_1_outputs)

# Generate a random bias for hidden layer 1
b_h1 = np.zeros((hidden_layer_1_outputs,1))

# Generate a random bias for hidden layer 2
b_h2 = np.zeros((hidden_layer_2_outputs,1))

 #calculate output of hidden layer 1
h1= f(np.dot(W_h1,X)+b_h1) 
display(h1.shape)

 #calculate output of hidden layer 2
h2= f(np.dot(W_h2,h1)+b_h2) 
display(h2.shape)
 


(4, 100)

(3, 100)

## Gradient descent in Numpy:
Let us now start training a neural network
We start by implementing a simple gradient descent for linear regression

In [0]:
num_inputs = 3
hidden_layer_1_outputs = 4
hidden_layer_2_outputs = 3
num_samples=10
max_iterations=200
f = lambda x: 1.0 /(1.0 + np.exp(-x))
X = np.random.rand(num_inputs,num_samples)
X=np.hstack((np.ones((X.shape[0],1)),X))
# Generate a random bias for hidden layer 1
b_h1 = np.zeros((hidden_layer_1_outputs,1))
# Generate a random bias for hidden layer 2
W_h1 = np.random.rand(hidden_layer_1_otputs,num_inputs+1)
#b_h1 = np.random.random()
W_h2 = np.random.random(hidden_layer_2_otputs,hidden_layer_1_otputs)
#b_h2 = np.random.random()
h1=f(np.dot(W_h1,X))
h2=f(np.dot(W_h2,h1))
alpha=0.01
ep=0.001
Y_gr=np.random.rand((hidden_layer_2_otputs,num_samples)                     
for j in range(max_iterations):        
          
  h1=f(np.dot(W_h1,X))
  # append columns with ones represented bias inputs
  h1= np.hstack((np.ones((h1.shape[0],1)),h1))                
  h2=f(np.dot(W_h2,h1))             
  J=np.sum(np.square(h2-Y_gr))
  hidden_error=h1[:,1:]*(1-h1[:,1:])*np.dot(J,W_h2.T[:,1:])
  grad_h2=h2*J
  grad_h1=h1*hidden_error
  total_hidden_gradient=np.average(grad_h2,axis=0)
  total_output_gradient_h1=np.average(grad_h1,axis=0)
  #total_output_gradient=np.average(output_pd,axis=0)
  W_h2 += -alpha*total_hidden_gradient_h2
  W_h1 +=-alpha*total_output_gradient_h1



 

SyntaxError: ignored

In [0]:
num_inputs = 3
hidden_layer_1_outputs = 4
hidden_layer_2_outputs = 3
num_samples=10
max_iterations=200
f = lambda x: 1.0 /(1.0 + np.exp(-x))
X = np.random.rand(num_samples,num_inputs-1)
X=np.hstack((np.ones((X.shape[0],1)),X))
# Generate a random bias for hidden layer 1
b_h1 = np.zeros((hidden_layer_1_outputs,1))
# Generate a random bias for hidden layer 2
W_h1 = np.random.rand(num_inputs,hidden_layer_1_outputs)
#b_h1 = np.random.random()
W_h2 = np.random.rand(hidden_layer_1_outputs+1,hidden_layer_2_outputs)
#b_h2 = np.random.random()


alpha=0.01
ep=0.001
Y_gr=np.random.rand(hidden_layer_2_outputs,num_samples)   
                    
for i in range(2):             
  h1=f(np.dot(X,W_h1))
  # append columns with ones represented bias inputs
  h1= np.hstack((np.ones((h1.shape[0],1)),h1))                
  h2=f(np.dot(h1,W_h2))  
                    #error
  J=np.sum(np.square(h2-Y_gr))
  grad_h2=h2*J
  #hidden_error=h1[:,1:]*(1-h1[:,1:])*np.dot(J,W_h2.T[:,1:])
  hidden_error = (h1[:, 1:] * (1 - h1[:, 1:])) * np.dot(grad_h2, W_h2.T[:, 1:]) 
  grad_h1=h1*hidden_error
  total_hidden_gradient_h2=np.average(grad_h2,axis=0)
  total_output_gradient_h1=np.average(grad_h1,axis=0)
  #total_output_gradient=np.average(output_pd,axis=0)
  W_h2 += -alpha*total_hidden_gradient_h2
  W_h1 +=-alpha*total_output_gradient_h1
  pritn('iter=',i)


    
 


ValueError: ignored

##Assignment 1
### Backpropagation in Numpy:
