<a href="https://colab.research.google.com/github/ahmadhajmosa/Machine-learning-labs/blob/daurmax/Copy_of_Session_1_working_version.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab on Machine Learning and Applications in Intelligent Vehicles
## Session 1: Introduction


In [0]:
import tensorflow

### Course Plan:

This lab is a continuation to the Machine learning lecture, the objective of this course is to learn how to model and implement neural networks using deep learning python frameworks: 
1. Tensorflow
2. Keras
3. Pytorch

Useing these frameworks, we will go through the following topics and use cases:

#### Session 1: 05.06 - 09:00 - 11:00  :

>#### Presentation:  05.06 - 09:00 - 10:30:
>1. Introduction to deep learning frameworks
2. Deep learning in Numpy

>#### Break:  05.06 - 10:30 - 10:45
>#### Assignment:  05.06 - 10:45 - 11:45 : 
>* Implementation of backprop using numpy

>1. Tensorflow backround 
2. Implementation of feedforward neural networks using Tensorflow

>#### Break:  05.06 - 10:00 - 10:15
>#### Assignment:  05.06 - 10:15 - 10:45 : 
  
  >* play around with tensorflow and build your first neural network



#### Session 2:  05.06 - 11:00 - 12:00  :

>#### Presentation:  05.06 - 11:00 - 12:00:


>3. Implementation of CNN useing Tensorflow
4. Tensorboard

>#### Break:  05.06 - 12:00 - 13:00
>#### Assignment:  05.06 - 13:00 - 13:30 :


 #### Session 3:  05.06 - 13:30 - 15:00  :

>#### Presentation:  05.06 - 13:00 - 14:00:

>5. Introduction to Keras
6. CNN using Keras
>#### Break:  05.06 - 14:00 - 14:15
>#### Assignment:  05.06 - 14:15 - 14:45 :

 #### Session 4:  05.06 - 15:00 - 16:30  :

>#### Presentation:  05.06 - 15:00 - 15:45:

>7. LSTM using Keras

>#### Break:  05.06 - 15:45 - 16:00
>#### Assignment:  05.06 - 16:00 - 16:30 :


8. VGG, Inceptaion, ResNet models using Keras

9. Autoencoders using Keras

10. Sequence to Sequence Models using Keras 

11. Attention Mechanism using Keras
12. GANS 
13. Introduction to Pytorch
14. Machine translation using Pytorch
15. Introduction to Allennlp
16. Deep Reinforcment Learning using Keras
17. Use case: building self driving car using Unity and tensorflow










#Session 1: 05.06 - 09:00 - 11:00 :




## Deep learning frameworks:

In the past decade, many deep learning frameworks have been developed to ease and scale the research and development of AI. Many big technology providers including Google, IBM, Microsoft and Facebook have entered the race to provide the best and most popluar frameworks. To enter such a race, mainly four features are considered in the provided framework:

1. Uses a popular language for data scientists (Python, Scale, C++ or R)
2. Flexible in creating and adjusting deep learning architectures -> Functional programming
3. Easy for computing gradients
4. Interface with GPUs for parallel processing


In the following we see the most popular provided deep learning frameworks with their providers
https://towardsdatascience.com/deep-learning-framework-power-scores-2018-23607ddf297a

![alt text](https://cdn-images-1.medium.com/max/1600/1*dYjDEI0mLpsCOySKUuX1VA.png)

## Tensorflow
TensorFlow is the undisputed heavyweight champion. It has the most GitHub activity, Google searches, Medium articles, books on Amazon and ArXiv articles. It also has the most developers using it and is listed in the most online job descriptions. TensorFlow is backed by Google.

## Keras
Keras has an “API designed for human beings, not machines.” It is the second most popular framework in nearly all evaluation areas. Keras sits on top of TensorFlow, Theano, or CNTK. Start with Keras if you are new to deep learning.

## Pytorch

PyTorch is the third most popular overall framework and the second most popular stand-alone framework. It is younger than TensorFlow and has grown rapidly in popularity. It allows customization that TensorFlow does not. It has the backing of Facebook.

## Theano

Theano was developed at the University of Montreal in 2007 and is the oldest significant Python deep learning framework. It has lost much of its popularity and its leader stated that major releases were no longer on the roadmap. However, updates continue to be made. Theano still the fifth highest scoring framework.

# Comparision:

## Criteria 1: Online Job Listings

TensorFlow is the clear winner when it comes to frameworks mentioned in job listings. Learn it if you want a job doing deep learning.

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*kA8dIgRqLdWgKgs2sd7clA.png)

## Criteria 2: Usage


Keras showed a surprising amount of use — nearly as much as TensorFlow. It’s interesting that US employers are overwhelmingly looking for TensorFlow skills, when — at least internationally — Keras is used almost as frequently.

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*6b2Tm0oFr99zKaxkr4g52w.png)
  
  
## Criteria 4: Google Search Activity

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*wpA6C9x_Nri42EzbqnS1fQ.png)

## Criteria 5: Medium Articles

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*Y1cJUgZTC3u_hU1lmdsroQ.png)


## Criteria 6: Amazon Books

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*mtP47q29T6agdkEoJcCw-w.png)

## Criteria 7 : ArXiv Articles

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*7jdNoNkGlx_1EnfevQXRvw.png)
  
## Criteria 8: GitHub Activity

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*eOOYV3C5klsuVBMX31ngxw.png)
  
 --------------------------------
 


  
 








```
# This is formatted as code
```


Before we jump into Tensorflow, we will implemented our first neural network model using Python Numpy package. NumPy is the fundamental package for scientific computing with Python, such as:

1. Linear Algebra
2. Statistics
3. Calculus

## A brief intro to Numpy operations:

1. Creating a Vector:
Here we use Numpy to create a 1-D Array which we then call a vector.





In [0]:
import numpy as np

v1 = np.zeros((1,100))
display(v1)

v2 = np.zeros((1,100))
display(v2)
v2.shape
# Trasposto
v2.T.shape

v3 = np.ones((1,100))
display(v3)

v4 = np.eye(4)
display(v4)

# Normal random generator
v5 = np.random.randn(100,1)
display(v5)
display('Mean of randn:', v5.mean())
display('Standard deviation of randn:', v5.std())
display('Min of randn:', v5.min())
display('Max of randn:', v5.max())


# Uniform random generator
v6 = np.random.rand(100,1)
display(v6)
display('Mean of randn:', v6.mean())
display('Standard deviation of randn:', v6.std())
display('Min of randn:', v6.min())
display('Max of randn:', v6.max())


2. Creating a Matrix
We Create a 2-D Array in Numpy and call it a Matrix. It contains 2 rows and 3 columns.

In [16]:
m1 = np.zeros((2,3))
display(m1)

matrix = np.array([[6,2,3],[4,5,6]])

display('matrix: ',matrix)
display('matrix shape:', matrix.shape)

array([[0., 0., 0.],
       [0., 0., 0.]])

'matrix: '

array([[1, 2, 3],
       [4, 5, 6]])

'matrix shape:'

(2, 3)

3. Selecting Elements


In [21]:

# First row, first column
display(matrix[0,0])

# First row, second column
display(matrix[0,1])

# First row, last column
display(matrix[0,-1])

# First row, second last column
display(matrix[0,-2])

# First row, from column 1 to the end
display(matrix[0,1:])

# First row, from beginning to column 2
display(matrix[0,0:2])

1

2

3

2

array([2, 3])

4. Describing a Matrix

In [22]:
# View the number of rows and columns
print(matrix.shape)

# View the number of elements (rows*columns)
print(matrix.size)

# View the number of dimensions (in this case two)
print(matrix.ndim)

(2, 3)
6
2


5. Finding the max and min values

In [28]:
display(matrix)

# General minimum and maximum
matrix.min()

# Minimum and maximum values of the first dimension
matrix.min(axis=0)

# Minimum and maximum values of the first dimension using Numpy
np.min(matrix, axis=1)
np.max(matrix, axis=1)

# Index of the maximum value
# The first one, for each column, returns the position of the maximum value 
# inside the column
display('arg', np.argmax(matrix, axis=0))
display('arg', np.max(matrix, axis=0))
display('arg', np.max(matrix))

# Search for specific condition
np.argwhere(matrix == np.max(matrix))
np.argwhere(matrix < np.max(matrix))

array([[1, 2, 3],
       [4, 5, 6]])

'arg'

array([1, 1, 1])

'arg'

array([4, 5, 6])

'arg'

6

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 1]])

6. Reshaping Arrays


In [32]:
matrix.shape

# Reshape the matrix (the number of elements should not change)
matrix.reshape((3,2))
matrix.reshape((6,1))
matrix.reshape((1,6))

# Dimension 0 is size 1, dimension 1 is size 2, dimension 2 is size 3
matrix.reshape((1,2,3))

# Dimension 0 is size 1, dimension 1 is calculated automatically,
# dimension 2 is size 3
matrix.reshape((1,-1,3)).shape

(1, 2, 3)

7. Calculating Dot Products

In [31]:
vector_1 = np.array([1,2,3])
vector_2 = np.array([4,5,6])

# Calculate dot product
print(np.dot(vector_1,vector_2))
# Alternative way using @
print(vector_1 @ vector_2)

32
32


##Linear regression in Numpy:

---



Write the numpy code for the following model:

$Y=WX+B$

where $X$ is 3x10 matrix:  10 samples and 3 features

$Y$ is 4x10 matrix: 10 samples and 4 outputs

$W$ is the weights matrix with the shape 4x3: connecting 3 inputs to 4 outputs

$b$ is a vector with a size 4 ( one bias per output)


In [36]:
# Inputs of features matrix
X = np.random.rand(3,10) 
display('shape of X',X.shape)

# Weights matrix
W = np.random.rand(4,3)

# Bias
# b = np.zeros(4,) # Vector (np.zeros(4,1) is a matrix with 1 column)
b = np.zeros((4,1))

# Regresion model
Y = np.dot(W,X) + b 
#4x3, 3x10 (the two numbers should match in order to have dot product)

display('Y:', Y)

'shape of X'

(3, 10)

'Y:'

array([[0.43817547, 0.2695894 , 0.37853434, 0.35512859, 0.45190805,
        0.35447867, 0.42456419, 0.43869521, 0.52544836, 0.55011926],
       [0.66190007, 0.64903426, 0.63937842, 0.63346361, 0.7279552 ,
        0.63759846, 0.80697221, 0.6567059 , 0.71911896, 0.732505  ],
       [0.74830109, 0.9064463 , 0.87489438, 1.01925684, 0.86342078,
        0.89666328, 1.11707612, 1.02071415, 0.85915731, 0.9917885 ],
       [0.93597497, 0.67285363, 0.77915296, 0.67015423, 0.97908297,
        0.74212055, 0.92624617, 0.78080294, 1.03830095, 1.00814051]])

## One neuron model in numpy:

A single neuron has multiple inputs and one output, in addition to the linear regression model, we need to add non linearity through an activation function:

$Y= f(WX+B)$

where $X$ is n x m matrix:  m samples and n features/inputs

$f(g)= \frac{1}{1+\exp(-g)}$  is a sigmoid acitavation function

$Y$ is nh1 x m matrix: m samples and ny outputs

$W$ is the weights matrix with the shape nh1 x n: connecting 3 inputs to 4 outputs

$b$ is a vector with a size nh1 ( one bias per output)





In [43]:
# One neuron per output, each connection is weighted

numb_inputs_1 = 3
numb_outputs_1 = 4
numb_inputs_2 = 4
numb_outputs_2 = 3
numb_samples = 100

# Activaction function using sigmoid
f = lambda x: 1.0/(1.0 + np.exp(-x))

# Another way to right a function
#def f(x):
#  return lambda x: 1.0/(1.0 + np.exp(-x))

# Same as linear regression
# Inputs of features matrix
X_1 = np.random.rand(numb_inputs_1,numb_samples) 
display('shape of X_1',X_1.shape)



# Weights matrix
W_1 = np.random.rand(numb_outputs_1,numb_inputs_1)
W_2 = np.random.rand(numb_outputs_2,numb_inputs_2)

# Bias
# b = np.zeros(4,) # Vector (np.zeros(4,1) is a matrix with 1 column)
b_1 = np.zeros((numb_outputs_1,1))
b_2 = np.zeros((numb_outputs_2,1))

# Regresion model (only difference, using the activation function)
Y_1 = f(np.dot(W_1,X_1) + b_1)
display(Y_1.shape)

Y_2 = f(np.dot(W_2,Y_1) + b_2)
display(Y_2.shape)

#4x3, 3x10 (the two numbers should match in order to have dot product)


'shape of X_1'

(3, 100)

(4, 100)

(3, 100)

## One hidden layer model in numpy:

The difference from the one neuron model is simple:  we need only to change the number of output "ny"

## Gradient descent in Numpy:
Let us now start training a neural network
We start by implementing a simple gradient descent for linear regression

##Assignment 1
### Backpropagation in Numpy:
