# Lab on Machine Learning and Applications in Intelligent Vehicles
## Session 1: Introduction


# Course Plan:

This lab is a continuation to the Machine learning lecture, the objective of this course is to learn how to model and implement neural networks using deep learning python frameworks: 
1. Tensorflow
2. Keras
3. Pytorch

Useing these frameworks, we will go through the following topics and use cases:

#### Session 1: 05.06 - 09:00 - 11:00  :

>#### Presentation:  05.06 - 09:00 - 10:30:
>1. Introduction to deep learning frameworks
2. Deep learning in Numpy

>#### Break:  05.06 - 10:30 - 10:45
>#### Assignment:  05.06 - 10:45 - 11:45 : 
>* Implementation of backprop using numpy

>1. Tensorflow backround 
2. Implementation of feedforward neural networks using Tensorflow

>#### Break:  05.06 - 10:00 - 10:15
>#### Assignment:  05.06 - 10:15 - 10:45 : 
  
  >* play around with tensorflow and build your first neural network



#### Session 2:  05.06 - 11:00 - 12:00  :

>#### Presentation:  05.06 - 11:00 - 12:00:


>3. Implementation of CNN useing Tensorflow
4. Tensorboard

>#### Break:  05.06 - 12:00 - 13:00
>#### Assignment:  05.06 - 13:00 - 13:30 :


 #### Session 3:  05.06 - 13:30 - 15:00  :

>#### Presentation:  05.06 - 13:00 - 14:00:

>5. Introduction to Keras
6. CNN using Keras
>#### Break:  05.06 - 14:00 - 14:15
>#### Assignment:  05.06 - 14:15 - 14:45 :

 #### Session 4:  05.06 - 15:00 - 16:30  :

>#### Presentation:  05.06 - 15:00 - 15:45:

>7. LSTM using Keras

>#### Break:  05.06 - 15:45 - 16:00
>#### Assignment:  05.06 - 16:00 - 16:30 :


8. VGG, Inceptaion, ResNet models using Keras

9. Autoencoders using Keras

10. Sequence to Sequence Models using Keras 

11. Attention Mechanism using Keras
12. GANS 
13. Introduction to Pytorch
14. Machine translation using Pytorch
15. Introduction to Allennlp
16. Deep Reinforcment Learning using Keras
17. Use case: building self driving car using Unity and tensorflow










#Session 1: 05.06 - 09:00 - 11:00 :




## Deep learning frameworks:

In the past decade, many deep learning frameworks have been developed to ease and scale the research and development of AI. Many big technology providers including Google, IBM, Microsoft and Facebook have entered the race to provide the best and most popluar frameworks. To enter such a race, mainly four features are considered in the provided framework:

1. Uses a popular language for data scientists (Python, Scale, C++ or R)
2. Flexible in creating and adjusting deep learning architectures -> Functional programming
3. Easy for computing gradients
4. Interface with GPUs for parallel processing


In the following we see the most popular provided deep learning frameworks with their providers
https://towardsdatascience.com/deep-learning-framework-power-scores-2018-23607ddf297a

![alt text](https://cdn-images-1.medium.com/max/1600/1*dYjDEI0mLpsCOySKUuX1VA.png)

## Tensorflow
TensorFlow is the undisputed heavyweight champion. It has the most GitHub activity, Google searches, Medium articles, books on Amazon and ArXiv articles. It also has the most developers using it and is listed in the most online job descriptions. TensorFlow is backed by Google.

## Keras
Keras has an “API designed for human beings, not machines.” It is the second most popular framework in nearly all evaluation areas. Keras sits on top of TensorFlow, Theano, or CNTK. Start with Keras if you are new to deep learning.

## Pytorch

PyTorch is the third most popular overall framework and the second most popular stand-alone framework. It is younger than TensorFlow and has grown rapidly in popularity. It allows customization that TensorFlow does not. It has the backing of Facebook.

## Theano

Theano was developed at the University of Montreal in 2007 and is the oldest significant Python deep learning framework. It has lost much of its popularity and its leader stated that major releases were no longer on the roadmap. However, updates continue to be made. Theano still the fifth highest scoring framework.

# Comparision:

## Criteria 1: Online Job Listings

TensorFlow is the clear winner when it comes to frameworks mentioned in job listings. Learn it if you want a job doing deep learning.

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*kA8dIgRqLdWgKgs2sd7clA.png)

## Criteria 2: Usage


Keras showed a surprising amount of use — nearly as much as TensorFlow. It’s interesting that US employers are overwhelmingly looking for TensorFlow skills, when — at least internationally — Keras is used almost as frequently.

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*6b2Tm0oFr99zKaxkr4g52w.png)
  
  
## Criteria 4: Google Search Activity

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*wpA6C9x_Nri42EzbqnS1fQ.png)

## Criteria 5: Medium Articles

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*Y1cJUgZTC3u_hU1lmdsroQ.png)


## Criteria 6: Amazon Books

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*mtP47q29T6agdkEoJcCw-w.png)

## Criteria 7 : ArXiv Articles

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*7jdNoNkGlx_1EnfevQXRvw.png)
  
## Criteria 8: GitHub Activity

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*eOOYV3C5klsuVBMX31ngxw.png)
  
 --------------------------------
 


  
 








```
# This is formatted as code
```


Before we jump into Tensorflow, we will implemented our first neural network model using Python Numpy package. NumPy is the fundamental package for scientific computing with Python, such as:

1. Linear Algebra
2. Statistics
3. Calculus

## A brief intro to Numpy operations:

1. Creating a Vector:
Here we use Numpy to create a 1-D Array which we then call a vector.





In [6]:
import numpy as np 

v1 = np.zeros((1,100))# array of 0's with a*b size 
display(v1)#

v2 = np.zeros((1,100))
#display(v2)

v2.T.shape

v3 = np.ones((1,100))
v4 = np.eye(4) #ident. mat.
v5 = np.random.randn(100,1) # normal random generator with mean 0 and 1 std
v6 = np.random.rand(100,1) # uniform random generator between 0 and 1

display(v4)
display('mean of randn:' ,v5.mean())
display('std of randn:' ,v5.std())

display('min of rand:', v6.min()) #-> gets the min of an array
display('max of rand:', v6.max()) #-> gets the max of an array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

'mean of randn:'

0.18764555008386424

'std of randn:'

1.1461888565253044

'min of rand:'

0.013743532898690347

'max of rand:'

0.9963112842927726

2. Creating a Matrix
We Create a 2-D Array in Numpy and call it a Matrix. It contains 2 rows and 3 columns.

In [8]:
# A matrix in python is a 2D array
## ROW*COL
m1 = np.zeros((2,3))
display(m1)

matrix = np.array([[6,2,3],[4,5,6]])
display(matrix)
matrix.argmax(axis=0)
display('matrix:',matrix)# shows the matrix
display('matrix shape:', matrix.shape) # length of array on each dim. of mat. m*n

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[6, 2, 3],
       [4, 5, 6]])

'matrix:'

array([[6, 2, 3],
       [4, 5, 6]])

'matrix shape:'

(2, 3)

3. Selecting Elements


In [10]:
display('matrix:',matrix)
# elements tart with index 0
display(matrix[0,0]) # first row fist col
# symbol '-' is used to pont to the last elemen
display(matrix[0,-1]) # first row last col
display(matrix[0,-2]) # first row second last col
# symbol ':' is used for segments frm A to B A:B (B not shown, stop one before)
display(matrix[0,1:]) # first row second to last col
display(matrix[0,:-1]) # first row second from col 0 - col 1
# in A:B, elements from A to one before B are shown
display(matrix[0,0:2]) # first row second from col 0 - col 1
display(matrix[-1,0:2]) # last row second from col 0 - col 1
# Element until one before the second last col.
display(matrix[0,:-2]) # first row second from col 0 - col 2


'matrix:'

array([[6, 2, 3],
       [4, 5, 6]])

6

3

2

array([2, 3])

array([6, 2])

array([6, 2])

array([4, 5])

array([6])

4. Describing a Matrix

In [0]:
#View the Number of Rows and Columns
print(matrix.shape)
#View the number of elements (rows*columns)
print(matrix.size)
#View the number of Dimensions(2 in this case)
print(matrix.ndim)

(2, 3)
6
2


5. Finding the max and min values

In [11]:
display('matrix:',matrix)
matrix.min(axis=0)

np.min(matrix, axis=1)
np.max(matrix, axis=1)
display('arg',np.argmax(matrix, axis=0))
display('max',np.max(matrix, axis=0))
display('max',np.argmax(matrix))

np.argwhere(matrix == np.max(matrix))
np.argwhere(matrix < np.max(matrix))




'matrix:'

array([[6, 2, 3],
       [4, 5, 6]])

'arg'

array([0, 1, 1])

'max'

array([6, 5, 6])

'max'

0

array([[0, 1],
       [0, 2],
       [1, 0],
       [1, 1]])

6. Reshaping Arrays


In [17]:
display('matrix:',matrix)
matrix.shape
display(matrix.reshape((3,2)))
display(matrix.reshape((6,1)))
matrix.reshape((1,6))
display(matrix.reshape((1,2,3)))  # dim 0 size = 1, dim 1 = 2, dim 2 = 3
display(matrix.reshape((1,-1,3)))  # dim 0 size = 1, dim 1 = 2, dim 2 = 3

'matrix:'

array([[6, 2, 3],
       [4, 5, 6]])

array([[6, 2],
       [3, 4],
       [5, 6]])

array([[6],
       [2],
       [3],
       [4],
       [5],
       [6]])

array([[[6, 2, 3],
        [4, 5, 6]]])

array([[[6, 2, 3],
        [4, 5, 6]]])

7. Calculating Dot Products

In [0]:

#Create vector-1
vector_1 = np.array([ 1,2,3 ])
#Create vector-2
vector_2 = np.array([ 4,5,6 ])

display(vector_1.shape)

## operations
#Calculate Dot Product
print(np.dot(vector_1,vector_2))
#Alternatively you can use @ to calculate dot products
print(vector_1 @ vector_2)

(3,)

32
32


##Linear regression in Numpy:

---



Write the numpy code for the following model:

$Y=WX+B$

where $X$ is 3x10 matrix:  10 samples and 3 features

$Y$ is 4x10 matrix: 10 samples and 4 outputs

$W$ is the weights matrix with the shape 4x3: connecting 3 inputs to 4 outputs

$b$ is a vector with a size 4 ( one bias per output)


In [18]:
# inputs or features matrix
X = np.random.rand(3,10)
display('shape of X', X.shape)

# weights matrix
W = np.random.rand(4,3)
display('shape of W', W.shape)

#bias 
b = np.zeros((4,1))

# regression model
Y= np.dot(W,X) + b # 4x3 , 3x10

display('Y:', Y.shape)


'shape of X'

(3, 10)

'shape of W'

(4, 3)

'Y:'

(4, 10)

## One neuron model in numpy:

A single neuron has multiple inputs and one output, in addition to the linear regression model, we need to add non linearity through an activation function:

$Y= f(WX+B)$

where $X$ is n x m matrix:  m samples and n features/inputs

$f(g)= \frac{1}{1+\exp(-g)}$  is a sigmoid acitavation function

$Y$ is nh1 x m matrix: m samples and ny outputs

$W$ is the weights matrix with the shape nh1 x n: connecting 3 inputs to 4 outputs

$b$ is a vector with a size nh1 ( one bias per output)





In [0]:
#def f(x):
    
    
#    return 1.0/(1.0 + np.exp(-x))
    
num_inputs = 3
num_outputs = 4
num_samples = 100

f = lambda x: 1.0/(1.0 + np.exp(-x)) # activation function (use sigmoid)


X = np.random.rand(num_inputs,num_samples)


# Generate a random weights vector
W = np.random.rand(num_outputs,num_inputs)


# Generate a random bias 
b = np.random.rand(num_outputs,1)

# Calculate Y
Y= f(np.dot(W,X) + b)
display(Y)
display(Y.shape)


## two hidden layers model in numpy:

The difference from the one neuron model is simple:  we need only to change the number of output "ny"

In [22]:
num_inputs = 3
hidden_layer_1_outputs = 4
hidden_layer_2_outputs = 3

num_samples = 100

f = lambda x: 1.0/(1.0 + np.exp(-x)) # activation function (use sigmoid)


X = np.random.rand(num_inputs,num_samples)


# Generate a random weights vector for the first hidden layer
W_h1 = np.random.rand(hidden_layer_1_outputs,num_inputs) #(4,3)
display(W_h1.shape)
# Generate a random weights vector for the second hidden layer
W_h2 = np.random.rand(hidden_layer_2_outputs,hidden_layer_1_outputs)#(3,4)
display(W_h2.shape)

# Generate a random bias for hidden layer 1
b_h1 = np.random.rand(hidden_layer_1_outputs,1)#(4,1)
display(b_h1.shape)
# Generate a random bias for hidden layer 1
b_h2 = np.random.rand(hidden_layer_2_outputs,1)#(3,1)
display(b_h2.shape)

# Calculate output of hidden layer 1
h1= f(np.dot(W_h1,X) + b_h1)
display(h1.shape)

# Calculate output of hidden layer 2
h2= f(np.dot(W_h2,h1) + b_h2)
display(h2.shape)


(4, 3)

(3, 4)

(4, 1)

(3, 1)

(4, 100)

(3, 100)

## Gradient descent in Numpy:
Let us now start training a neural network
We start by implementing a simple gradient descent for linear regression

In [0]:
converged = False
iter = 0
m = 10 # Number of samples
ni= 1 # Number of input neurons
h = 1 # Number of hidden layers
no =1 # Number of neurons in the output layer

# Generate a random X (we do not have a real data)
X = np.random.rand(m)
display(X)

# learning rate
alpha =0.01

# early stop criteria 
ep=0.001

# maximum number of training iterations
max_iter=100

# Generate a random weights vector for the output layer
W1 = np.random.rand()

# Generate a random bias for the output layer 
b1 = np.random.rand()

# Generate a random ground truth
Y_gr = np.random.rand(m)


J = sum([(b1 + W1*X[i] - Y_gr[i])**2 for i in range(m)]) #cost function sum of squared error

while not converged: #while converged == false
        print('Interations:' , iter)
        
        # for each training sample, compute the gradient (d/d_theta j(theta))
        grad0 = 1.0/m * sum([(b1 + W1*X[i] - Y_gr[i]) for i in range(m)]) 
        grad1 = 1.0/m * sum([(b1 + W1*X[i] - Y_gr[i])*X[i] for i in range(m)])
        
        # update the theta_temp
        temp0 = b1 - alpha * grad0
        temp1 = W1 - alpha * grad1
        # update theta
        b1 = temp0
        W1 = temp1
        
        # sum squared error
        e = sum([(b1 + W1*X[i] - Y_gr[i])**2 for i in range(m)]) 
        print('Error:', e)

        if abs(J-e) <= ep:
            print('Converged, iterations: ', iter, '!!!')
            converged = True
    
        J = e   # update error 
        iter += 1  # update iter
    
        if iter == max_iter:
            print('Max interactions exceeded!')
            converged = True

array([0.53091603, 0.02136871, 0.70365119, 0.51861253, 0.35910505,
       0.05090667, 0.12236431, 0.5057064 , 0.0405531 , 0.68880744])

Interations: 0
Error: 1.5336202670136696
Interations: 1
Error: 1.532250544115727
Interations: 2
Error: 1.5308874282609115
Interations: 3
Error: 1.5295307992259914
Interations: 4
Error: 1.5281805394634522
Interations: 5
Error: 1.5268365340412329
Interations: 6
Error: 1.525498670583815
Interations: 7
Error: 1.5241668392146464
Interations: 8
Error: 1.5228409324998537
Interations: 9
Error: 1.5215208453932332
Interations: 10
Error: 1.5202064751824715
Interations: 11
Error: 1.5188977214365869
Interations: 12
Error: 1.5175944859545503
Interations: 13
Error: 1.5162966727150646
Interations: 14
Error: 1.5150041878274785
Interations: 15
Error: 1.5137169394838026
Interations: 16
Error: 1.5124348379118115
Interations: 17
Error: 1.5111577953291981
Interations: 18
Error: 1.5098857258987652
Interations: 19
Error: 1.508618545684625
Interations: 20
Error: 1.5073561726093858
Interations: 21
Error: 1.5060985264123032
Interations: 22
Error: 1.5048455286083766
Interations: 23
Error: 1.5035971024483639
Inter

##Assignment 1
### Backpropagation in Numpy:


In [0]:
num_inputs = 4
hidden_layer_1_outputs = 4
hidden_layer_2_outputs = 3

num_samples = 10

f = lambda x: 1.0/(1.0 + np.exp(-x)) # activation function (use sigmoid)


X = np.random.rand(num_samples,num_inputs-1) # 10x4

X = np.hstack((np.ones((X.shape[0], 1)), X))

display(X.shape)

# Generate a random weights vector for the first hidden layer
W_h1 = np.random.rand(num_inputs,hidden_layer_1_outputs) # 4x4

# Generate a random weights vector for the second hidden layer
W_h2 = np.random.rand(hidden_layer_1_outputs+1,hidden_layer_2_outputs)




# Calculate output of hidden layer 1
h1= f(np.dot(X,W_h1))
display(h1.shape)

# Calculate output of hidden layer 2
#h2= f(np.dot(h1,W_h2))
#display(h2.shape)


# learning rate
alpha =0.01

# early stop criteria 
ep=0.001


# maximum number of training iterations
max_iter=100

# Generate a random ground truth
Y_gr = np.random.rand(hidden_layer_2_outputs,num_samples)

#J = sum([(h2 - Y_gr[:,i])**2 for i in range(num_samples)]) #cost function sum of squared error
print(J)

#while not converged:
for i in range(100):
        #print('Interations:' , iter)
    
        # forward prop   
        # Calculate output of hidden layer 1
        h1= f(np.dot(X,W_h1))
        
        # append a column with ones representing bias inputs
        h1 = np.hstack((np.ones((h1.shape[0], 1)), h1))
        # Calculate output of hidden layer 2
        h2= f(np.dot(h1,W_h2))
        
        
        #error/error 
               
        J = np.sum(np.square(h2- Y_gr.T))
        
        # gradient of the output layer
        grad_h2 = h2*J
        
      
        # error
        
        #display('h1', (h1[:, 1:] * (1 - h1[:, 1:])).shape)
        
        
        #display('dot ', np.dot(grad_h2, W_h2.T[:, 1:]).shape)


        hidden_error = (h1[:, 1:] * (1 - h1[:, 1:])) * np.dot(grad_h2, W_h2.T[:, 1:]) 

        #print(h1.shape)
        #print(hidden_error.shape)
        grad_h1= h1[:, :, np.newaxis]*hidden_error[:, np.newaxis, :]

      
        # average gradient
        total_hidden_gradient_h2 = np.average(grad_h2, axis=0)
        total_output_gradient_h1 = np.average(grad_h1, axis=0)
        #print(grad_h1.shape)
        #print(W_h1.shape)

        # update weights
        W_h2 += - alpha * total_hidden_gradient_h2
        W_h1 += - alpha * total_output_gradient_h1[1:,:]
        
        
        print('iter',i)
        
        print('cost',J)