In [5]:
import tensorflow
print('HelloWorld')

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

HelloWorld


# Lab on Machine Learning and Applications in Intelligent Vehicles
## Session 1: Introduction


### Course Plan:

This lab is a continuation to the Machine learning lecture, the objective of this course is to learn how to model and implement neural networks using deep learning python frameworks: 
1. Tensorflow
2. Keras
3. Pytorch

Useing these frameworks, we will go through the following topics and use cases:

#### Session 1: 05.06 - 09:00 - 11:00  :

>#### Presentation:  05.06 - 09:00 - 10:30:
>1. Introduction to deep learning frameworks
2. Deep learning in Numpy

>#### Break:  05.06 - 10:30 - 10:45
>#### Assignment:  05.06 - 10:45 - 11:45 : 
>* Implementation of backprop using numpy

>1. Tensorflow backround 
2. Implementation of feedforward neural networks using Tensorflow

>#### Break:  05.06 - 10:00 - 10:15
>#### Assignment:  05.06 - 10:15 - 10:45 : 
  
  >* play around with tensorflow and build your first neural network



#### Session 2:  05.06 - 11:00 - 12:00  :

>#### Presentation:  05.06 - 11:00 - 12:00:


>3. Implementation of CNN useing Tensorflow
4. Tensorboard

>#### Break:  05.06 - 12:00 - 13:00
>#### Assignment:  05.06 - 13:00 - 13:30 :


 #### Session 3:  05.06 - 13:30 - 15:00  :

>#### Presentation:  05.06 - 13:00 - 14:00:

>5. Introduction to Keras
6. CNN using Keras
>#### Break:  05.06 - 14:00 - 14:15
>#### Assignment:  05.06 - 14:15 - 14:45 :

 #### Session 4:  05.06 - 15:00 - 16:30  :

>#### Presentation:  05.06 - 15:00 - 15:45:

>7. LSTM using Keras

>#### Break:  05.06 - 15:45 - 16:00
>#### Assignment:  05.06 - 16:00 - 16:30 :


8. VGG, Inceptaion, ResNet models using Keras

9. Autoencoders using Keras

10. Sequence to Sequence Models using Keras 

11. Attention Mechanism using Keras
12. GANS 
13. Introduction to Pytorch
14. Machine translation using Pytorch
15. Introduction to Allennlp
16. Deep Reinforcment Learning using Keras
17. Use case: building self driving car using Unity and tensorflow










#Session 1: 05.06 - 09:00 - 11:00 :




## Deep learning frameworks:

In the past decade, many deep learning frameworks have been developed to ease and scale the research and development of AI. Many big technology providers including Google, IBM, Microsoft and Facebook have entered the race to provide the best and most popluar frameworks. To enter such a race, mainly four features are considered in the provided framework:

1. Uses a popular language for data scientists (Python, Scale, C++ or R)
2. Flexible in creating and adjusting deep learning architectures -> Functional programming
3. Easy for computing gradients
4. Interface with GPUs for parallel processing


In the following we see the most popular provided deep learning frameworks with their providers
https://towardsdatascience.com/deep-learning-framework-power-scores-2018-23607ddf297a

![alt text](https://cdn-images-1.medium.com/max/1600/1*dYjDEI0mLpsCOySKUuX1VA.png)

## Tensorflow
TensorFlow is the undisputed heavyweight champion. It has the most GitHub activity, Google searches, Medium articles, books on Amazon and ArXiv articles. It also has the most developers using it and is listed in the most online job descriptions. TensorFlow is backed by Google.

## Keras
Keras has an “API designed for human beings, not machines.” It is the second most popular framework in nearly all evaluation areas. Keras sits on top of TensorFlow, Theano, or CNTK. Start with Keras if you are new to deep learning.

## Pytorch

PyTorch is the third most popular overall framework and the second most popular stand-alone framework. It is younger than TensorFlow and has grown rapidly in popularity. It allows customization that TensorFlow does not. It has the backing of Facebook.

## Theano

Theano was developed at the University of Montreal in 2007 and is the oldest significant Python deep learning framework. It has lost much of its popularity and its leader stated that major releases were no longer on the roadmap. However, updates continue to be made. Theano still the fifth highest scoring framework.

# Comparision:

## Criteria 1: Online Job Listings

TensorFlow is the clear winner when it comes to frameworks mentioned in job listings. Learn it if you want a job doing deep learning.

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*kA8dIgRqLdWgKgs2sd7clA.png)

## Criteria 2: Usage


Keras showed a surprising amount of use — nearly as much as TensorFlow. It’s interesting that US employers are overwhelmingly looking for TensorFlow skills, when — at least internationally — Keras is used almost as frequently.

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*6b2Tm0oFr99zKaxkr4g52w.png)
  
  
## Criteria 4: Google Search Activity

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*wpA6C9x_Nri42EzbqnS1fQ.png)

## Criteria 5: Medium Articles

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*Y1cJUgZTC3u_hU1lmdsroQ.png)


## Criteria 6: Amazon Books

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*mtP47q29T6agdkEoJcCw-w.png)

## Criteria 7 : ArXiv Articles

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*7jdNoNkGlx_1EnfevQXRvw.png)
  
## Criteria 8: GitHub Activity

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*eOOYV3C5klsuVBMX31ngxw.png)
  
 --------------------------------
 


  
 








```
# This is formatted as code
```


Before we jump into Tensorflow, we will implemented our first neural network model using Python Numpy package. NumPy is the fundamental package for scientific computing with Python, such as:

1. Linear Algebra
2. Statistics
3. Calculus

## A brief intro to Numpy operations:

1. Creating a Vector:
Here we use Numpy to create a 1-D Array which we then call a vector.





In [24]:
import numpy as np

v1=np.zeros((1,100))
display(v1)

v2=np.ones((1,100))
display(v2)

display(v2.shape)
display(v2.T.shape) # Transpose

v4 = np.eye(4)
display(v4)

v5 = np.random.randn(100,1) # random generator normal distributed, zero mean standard deviation
v6 = np.random.rand(100,1) # random generator uniform

#display(v5)
display('Mean of randn: ', v5.mean())
display('Std of randn: ', v5.std())

display('min of rand: ',v6.min())
display('max of rand: ' ,v6.max())

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

(1, 100)

(100, 1)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

'Mean of randn: '

0.009512383523836416

'Std of randn: '

1.0075142887216684

'min of rand: '

0.0028674418479257557

'max of rand: '

0.9814485975581609

2. Creating a Matrix
We Create a 2-D Array in Numpy and call it a Matrix. It contains 2 rows and 3 columns.

In [27]:
m1 = np.zeros((2,3))
display(m1)

matrix = np.array([[1,2,3],[4,5,6]])
display('Matrix: ',matrix)
display('Matrix shape: ',matrix.shape)

array([[0., 0., 0.],
       [0., 0., 0.]])

'Matrix: '

array([[1, 2, 3],
       [4, 5, 6]])

'Matrix shape: '

(2, 3)

3. Selecting Elements


In [33]:

display(matrix[0]) # first row
display(matrix[0,1]) # first row second column
display(matrix[0,-1]) # last element in the dimension
display(matrix[0,-2]) # one before the last element in the dimension
display(matrix[0,1:]) # one to the end
display(matrix[0,0:2]) # zero to one!!! 
display(matrix[-1,0:2]) # zero to one!!! - last row

array([1, 2, 3])

2

3

2

array([2, 3])

matrix[0] # first row4. Describing a Matrix

In [34]:
print(matrix.shape) # View the nuber of rows and columns
print(matrix.size) # View the number of elements
print(matrix.ndim) # View the number of dimensions

(2, 3)
6
2


5. Finding the max and min values

In [45]:
display(matrix)
display(matrix.min()) # whole matrix
display(matrix.min(axis=0)) # first dimension - row

display(np.min(matrix, axis=0))

display(np.max(matrix, axis=0)) # Maximum value per column
display(np.argmax(matrix, axis=0)) # Index of the maximum value

display(np.argmax(matrix, axis=1)) # Index of the macimum per row

np.argwhere(matrix == np.max(matrix)) # Indexes of condition
np.argwhere(matrix < np.max(matrix))
display(np.where(matrix == np.max(matrix)))



array([[1, 2, 3],
       [4, 5, 6]])

1

array([1, 2, 3])

array([1, 2, 3])

array([4, 5, 6])

array([1, 1, 1])

array([2, 2])

(array([1]), array([2]))

6. Reshaping Arrays


In [49]:
matrix.shape
matrix.reshape((3,2))
matrix.reshape((6,1))
matrix.reshape((1,2,3)) # 3D matrix dimesion 0 size=1, dim=1, size=2 ...
matrix.reshape((1,-1,3)).shape # automatic calculation of dim=1

(1, 2, 3)

7. Calculating Dot Products

In [50]:
vec1 = np.array([1,2,3])
vec2 = np.array([3,4,5])

print(np.dot(vec1,vec2)) # do product
print(vec1 @ vec2) # alternative notation

26
26


##Linear regression in Numpy:

---



Write the numpy code for the following model:

$Y=WX+B$

where $X$ is 3x10 matrix:  10 samples and 3 features

$Y$ is 4x10 matrix: 10 samples and 4 outputs

$W$ is the weights matrix with the shape 4x3: connecting 3 inputs to 4 outputs

$b$ is a vector with a size 4 ( one bias per output)


In [55]:
# inputs of the feature matrix
X = np.random.rand(3,10)
display('shape of X', X.shape)

# weights of the feature matrix
W = np.random.rand(4,3)

# bias matrix
b = np.zeros((4,1))

# regression model
Y = np.dot(W,X) + b # 4x3, 3x10 -> 4x10

display('Y: ',Y.shape)



'shape of X'

(3, 10)

'Y: '

(4, 10)

## One neuron model in numpy:

A single neuron has multiple inputs and one output, in addition to the linear regression model, we need to add non linearity through an activation function:

$Y= f(WX+B)$

where $X$ is n x m matrix:  m samples and n features/inputs

$f(g)= \frac{1}{1+\exp(-g)}$  is a sigmoid acitavation function

$Y$ is nh1 x m matrix: m samples and ny outputs

$W$ is the weights matrix with the shape nh1 x n: connecting 3 inputs to 4 outputs

$b$ is a vector with a size nh1 ( one bias per output)





In [0]:
#def f(x):
#  return x:1.0/(1.0+ np.exp(-x))

num_in = 3
num_out = 4
num_samples = 100

f = lambda x:1.0/(1.0+ np.exp(-x)) # activaion function sigmoid

# inputs of the feature matrix
X = np.random.rand(num_in,num_samples)
display('shape of X', X.shape)

# weights of the feature matrix
W = np.random.rand(num_out,num_in)

# bias matrix
b = np.zeros((num_out,1))

# regression model
Y = f(np.dot(W,X) + b) # 4x3, 3x10 -> 4x10

display('Y: ',Y.shape)
display(Y)

## One hidden layer model in numpy:

The difference from the one neuron model is simple:  we need only to change the number of output "ny"

In [65]:
#def f(x):
#  return x:1.0/(1.0+ np.exp(-x))

num_in = 3
num_out_hidden_1 = 3
num_out_hidden_2 = 4
num_samples = 100

f = lambda x:1.0/(1.0+ np.exp(-x)) # activaion function sigmoid

# inputs of the feature matrix
X0 = np.random.rand(num_in,num_samples)
display('shape of X', X.shape)

# weights of the feature matrix
W0 = np.random.rand(num_out_hidden_1,num_in)

# bias matrix
b0 = np.zeros((num_out_hidden_1,1))

# regression model
Y0 = f(np.dot(W0,X0) + b0) # 4x3, 3x10 -> 4x10

# inputs of the feature matrix
X1 = Y0
display('shape of X', X.shape)

# weights of the feature matrix
W1 = np.random.rand(num_out_hidden_2,num_out_hidden_1)

# bias matrix
b1 = np.zeros((num_out_hidden_2,1))

# regression model
Y2 = f(np.dot(W1,X1) + b1) # 4x3, 3x10 -> 4x10

display('Y: ',Y.shape)
display(Y)

'shape of X'

(3, 100)

'shape of X'

(3, 100)

'Y: '

(1, 100)

array([[0.61286108, 0.69280677, 0.85982471, 0.8172959 , 0.6538321 ,
        0.76209834, 0.7947148 , 0.67433103, 0.78242926, 0.82027352,
        0.74927043, 0.78057883, 0.73850673, 0.69144081, 0.77257157,
        0.82550706, 0.72143867, 0.76256073, 0.66522869, 0.75843298,
        0.81676783, 0.75652419, 0.78566821, 0.79235022, 0.82626652,
        0.86653717, 0.72273847, 0.87514678, 0.74927786, 0.86057543,
        0.88374421, 0.77744287, 0.87003161, 0.89471482, 0.76788946,
        0.80274549, 0.73357708, 0.79793838, 0.81076145, 0.84869794,
        0.68066985, 0.51818863, 0.78891879, 0.78483609, 0.88726899,
        0.86071046, 0.71202786, 0.79103555, 0.89385643, 0.76347763,
        0.67537019, 0.71718627, 0.80181476, 0.75621113, 0.81111556,
        0.83751386, 0.6613573 , 0.64986501, 0.75897393, 0.86971107,
        0.71326921, 0.80136255, 0.79302795, 0.71115459, 0.69921674,
        0.82089223, 0.85083384, 0.76717118, 0.6999393 , 0.80646439,
        0.83842779, 0.70711794, 0.68431111, 0.86

## Gradient descent in Numpy:
Let us now start training a neural network
We start by implementing a simple gradient descent for linear regression

##Assignment 1
### Backpropagation in Numpy:
