In [6]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

# Lab on Machine Learning and Applications in Intelligent Vehicles
## Session 1: Introduction


### Course Plan:

This lab is a continuation to the Machine learning lecture, the objective of this course is to learn how to model and implement neural networks using deep learning python frameworks: 
1. Tensorflow
2. Keras
3. Pytorch

Useing these frameworks, we will go through the following topics and use cases:

#### Session 1: 05.06 - 09:00 - 11:00  :

>#### Presentation:  05.06 - 09:00 - 10:30:
>1. Introduction to deep learning frameworks
2. Deep learning in Numpy

>#### Break:  05.06 - 10:30 - 10:45
>#### Assignment:  05.06 - 10:45 - 11:45 : 
>* Implementation of backprop using numpy

>1. Tensorflow backround 
2. Implementation of feedforward neural networks using Tensorflow

>#### Break:  05.06 - 10:00 - 10:15
>#### Assignment:  05.06 - 10:15 - 10:45 : 
  
  >* play around with tensorflow and build your first neural network



#### Session 2:  05.06 - 11:00 - 12:00  :

>#### Presentation:  05.06 - 11:00 - 12:00:


>3. Implementation of CNN useing Tensorflow
4. Tensorboard

>#### Break:  05.06 - 12:00 - 13:00
>#### Assignment:  05.06 - 13:00 - 13:30 :


 #### Session 3:  05.06 - 13:30 - 15:00  :

>#### Presentation:  05.06 - 13:00 - 14:00:

>5. Introduction to Keras
6. CNN using Keras
>#### Break:  05.06 - 14:00 - 14:15
>#### Assignment:  05.06 - 14:15 - 14:45 :

 #### Session 4:  05.06 - 15:00 - 16:30  :

>#### Presentation:  05.06 - 15:00 - 15:45:

>7. LSTM using Keras

>#### Break:  05.06 - 15:45 - 16:00
>#### Assignment:  05.06 - 16:00 - 16:30 :


8. VGG, Inceptaion, ResNet models using Keras

9. Autoencoders using Keras

10. Sequence to Sequence Models using Keras 

11. Attention Mechanism using Keras
12. GANS 
13. Introduction to Pytorch
14. Machine translation using Pytorch
15. Introduction to Allennlp
16. Deep Reinforcment Learning using Keras
17. Use case: building self driving car using Unity and tensorflow










#Session 1: 05.06 - 09:00 - 11:00 :




## Deep learning frameworks:

In the past decade, many deep learning frameworks have been developed to ease and scale the research and development of AI. Many big technology providers including Google, IBM, Microsoft and Facebook have entered the race to provide the best and most popluar frameworks. To enter such a race, mainly four features are considered in the provided framework:

1. Uses a popular language for data scientists (Python, Scale, C++ or R)
2. Flexible in creating and adjusting deep learning architectures -> Functional programming
3. Easy for computing gradients
4. Interface with GPUs for parallel processing


In the following we see the most popular provided deep learning frameworks with their providers
https://towardsdatascience.com/deep-learning-framework-power-scores-2018-23607ddf297a

![alt text](https://cdn-images-1.medium.com/max/1600/1*dYjDEI0mLpsCOySKUuX1VA.png)

## Tensorflow
TensorFlow is the undisputed heavyweight champion. It has the most GitHub activity, Google searches, Medium articles, books on Amazon and ArXiv articles. It also has the most developers using it and is listed in the most online job descriptions. TensorFlow is backed by Google.

## Keras
Keras has an “API designed for human beings, not machines.” It is the second most popular framework in nearly all evaluation areas. Keras sits on top of TensorFlow, Theano, or CNTK. Start with Keras if you are new to deep learning.

## Pytorch

PyTorch is the third most popular overall framework and the second most popular stand-alone framework. It is younger than TensorFlow and has grown rapidly in popularity. It allows customization that TensorFlow does not. It has the backing of Facebook.

## Theano

Theano was developed at the University of Montreal in 2007 and is the oldest significant Python deep learning framework. It has lost much of its popularity and its leader stated that major releases were no longer on the roadmap. However, updates continue to be made. Theano still the fifth highest scoring framework.

# Comparision:

## Criteria 1: Online Job Listings

TensorFlow is the clear winner when it comes to frameworks mentioned in job listings. Learn it if you want a job doing deep learning.

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*kA8dIgRqLdWgKgs2sd7clA.png)

## Criteria 2: Usage


Keras showed a surprising amount of use — nearly as much as TensorFlow. It’s interesting that US employers are overwhelmingly looking for TensorFlow skills, when — at least internationally — Keras is used almost as frequently.

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*6b2Tm0oFr99zKaxkr4g52w.png)
  
  
## Criteria 4: Google Search Activity

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*wpA6C9x_Nri42EzbqnS1fQ.png)

## Criteria 5: Medium Articles

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*Y1cJUgZTC3u_hU1lmdsroQ.png)


## Criteria 6: Amazon Books

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*mtP47q29T6agdkEoJcCw-w.png)

## Criteria 7 : ArXiv Articles

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*7jdNoNkGlx_1EnfevQXRvw.png)
  
## Criteria 8: GitHub Activity

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*eOOYV3C5klsuVBMX31ngxw.png)
  
 --------------------------------
 


  
 








```
# This is formatted as code
```


Before we jump into Tensorflow, we will implemented our first neural network model using Python Numpy package. NumPy is the fundamental package for scientific computing with Python, such as:

1. Linear Algebra
2. Statistics
3. Calculus

## A brief intro to Numpy operations:

1. Creating a Vector:
Here we use Numpy to create a 1-D Array which we then call a vector.





In [32]:
import numpy as np

v1 = np.zeros((1,100))
#display(v1)
v2 = np.zeros((1,100))
#display(v2)
v2.shape
# transport
v2.T.shape
v4 = np.eye((4))
#display(v4)
v5 = np.random.randn(100,1) # normal random generator
v6 = np.random.rand(100,1) # uniform random generator
#display(v6)
#display(v5)
display('mean of randn:',v5.mean())
display('std of randn:',v5.std())

display('std of randn:',v6.min())
display('std of randn:',v6.min())

display('mean of randn:',v6.max())
display('std of randn:',v6.max())


'mean of randn:'

0.03790170488208862

'std of randn:'

1.0044544036633825

'std of randn:'

0.004692792117357847

'std of randn:'

0.004692792117357847

'mean of randn:'

0.9804700440846881

'std of randn:'

0.9804700440846881

2. Creating a Matrix
We Create a 2-D Array in Numpy and call it a Matrix. It contains 2 rows and 3 columns.

In [39]:
m1 = np.zeros((2,3))
#display(m1)

matrix = np.array([[1,2,3],[4,5,6]])
display(matrix)
display('matrix shape:', matrix.shape)

array([[1, 2, 3],
       [4, 5, 6]])

'matrix shape:'

(2, 3)

3. Selecting Elements


In [46]:
display(matrix[0,0]) # first row first col
display(matrix[0,-1]) # first row last col
display(matrix[0,-2]) # first row second last col
display(matrix[0,1:]) # first row second last col
display(matrix[0,:-1]) # first row second from col 0 -col 1
display(matrix[0,0:2]) # first row second from col 0 -col 1

1

3

2

array([2, 3])

array([1, 2])

array([1, 2])

4. Describing a Matrix

In [47]:
print(matrix.shape) # view the number of rows and columns
print(matrix.size) # view the number of elements (rows*columns)
print(matrix.ndim) # view the nubmer of dimensions (2 in this case)

(2, 3)
6
2


5. Finding the max and min values

In [57]:
#display(matrix)
matrix.min(axis=0) # view the min element of row

np.min(matrix, axis=1)
np.max(matrix, axis=1)
#display('arg', np.argmax(matrix, axis=0))
#display('max', np.max(matrix, axis=0))

np.argwhere(matrix == np.max(matrix))
np.argwhere(matrix < np.max(matrix))


array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 1]])

6. Reshaping Arrays


In [68]:
matrix.shape
matrix.reshape((3,2))
matrix.reshape((6,1))
matrix.reshape((1,6))
matrix.reshape((1,2,3)) # dim 0 size = 1, dim 1=2, dim 


array([[[1, 2, 3],
        [4, 5, 6]]])

7. Calculating Dot Products

In [72]:
# create matrix
vector_1 = np.array([1,2,3])
vector_2 = np.array([4,5,6])

print(np.dot(vector_1,vector_2))
# alternatively you can use @ to calculate dot products


print(np.dot(vector_1 @ vector_2))


32


TypeError: ignored

##Linear regression in Numpy:

---



Write the numpy code for the following model:

$Y=WX+B$

where $X$ is 3x10 matrix:  10 samples and 3 features

$Y$ is 4x10 matrix: 10 samples and 4 outputs

$W$ is the weights matrix with the shape 4x3: connecting 3 inputs to 4 outputs

$b$ is a vector with a size 4 ( one bias per output)


In [79]:
# inputs of features matrix

X = np.random.rand(3,10)
display('shape of X', X.shape)

# Weights matrix

W = np.random.rand(4,3)

# bias

b = np.zeros((4,1))

# regression model

Y = np.dot(W,X) + b
display(Y)
display('Y:', Y.shape)

'shape of X'

(3, 10)

array([[0.59893439, 0.37267232, 0.66005716, 0.54656477, 0.29742939,
        0.30503663, 0.46318925, 0.43961454, 0.53544335, 0.64563852],
       [0.68464208, 0.47292609, 0.81835809, 0.63552962, 0.39686407,
        0.30724372, 0.6005141 , 0.47477745, 0.72175546, 0.8254916 ],
       [0.87024378, 0.46288787, 0.90203691, 0.75251555, 0.36680517,
        0.44797393, 0.70482911, 0.69303398, 0.8063879 , 0.92677663],
       [0.64568712, 0.25485598, 0.56281747, 0.53137801, 0.17321787,
        0.3923898 , 0.43135942, 0.56878687, 0.45103594, 0.56062562]])

'Y:'

(4, 10)

## One neuron model in numpy:

A single neuron has multiple inputs and one output, in addition to the linear regression model, we need to add non linearity through an activation function:

$Y= f(WX+B)$

where $X$ is n x m matrix:  m samples and n features/inputs

$f(g)= \frac{1}{1+\exp(-g)}$  is a sigmoid acitavation function

$Y$ is nh1 x m matrix: m samples and ny outputs

$W$ is the weights matrix with the shape nh1 x n: connecting 3 inputs to 4 outputs

$b$ is a vector with a size nh1 ( one bias per output)





In [95]:
num_inputs = 3
num_outputs = 4
num_samples = 100






f = lambda x: 1.0/(1.0 + np.exp(-x)) # activation function (use sigmod function)

X = np.random.rand(num_inputs,num_samples)

# Generate a random weights 

W = np.random.rand(num_outputs, num_inputs)

# Generate a rondom bias
b = np.zeros((num_outputs,1))

# calculate y

Y = f(np.dot(W,X) + b)
display(Y)



array([[0.66154576, 0.83866781, 0.71215531, 0.81212233, 0.81956725,
        0.7249126 , 0.72458121, 0.77342191, 0.81527662, 0.57207404,
        0.77693399, 0.77133045, 0.69516122, 0.63177557, 0.76492437,
        0.61498484, 0.70432857, 0.82406645, 0.73226071, 0.82952944,
        0.68876137, 0.72633858, 0.80781258, 0.75508194, 0.76158457,
        0.75637852, 0.80837369, 0.65141928, 0.73332112, 0.79262832,
        0.61442165, 0.77112296, 0.72271607, 0.79101449, 0.68345094,
        0.76165637, 0.60382765, 0.78735511, 0.78172674, 0.72996252,
        0.6867335 , 0.69184839, 0.76387216, 0.62943424, 0.7744539 ,
        0.73278428, 0.83082873, 0.83398126, 0.6852579 , 0.68696927,
        0.8506456 , 0.80842458, 0.71362367, 0.76043218, 0.79875406,
        0.65593601, 0.65639969, 0.81953987, 0.75857445, 0.73984435,
        0.61297269, 0.71492148, 0.83871   , 0.72307374, 0.66206972,
        0.79567386, 0.59459747, 0.80919605, 0.87767113, 0.74807018,
        0.80588877, 0.66306147, 0.69407207, 0.85

## Two hidden layers model in numpy:

The difference from the one neuron model is simple:  we need only to change the number of output "ny"

In [101]:
num_inputs = 3
hidden_layer_1_outputs = 4
hidden_layer_2_outputs = 3

num_samples = 100





f = lambda x: 1.0/(1.0 + np.exp(-x)) # activation function (use sigmod function)

X = np.random.rand(num_inputs,num_samples)

# Generate a random weights vector for the first hidden layer

W_h1 = np.random.rand(hidden_layer_1_outputs, num_inputs)

# Generate a random weights vector for the second hidden layer

W_h2 = np.random.rand(hidden_layer_2_outputs,hidden_layer_1_outputs)

# Generate a random bias
b_h1= np.zeros((hidden_layer_1_outputs, 1))

b_h2= np.zeros((hidden_layer_2_outputs, 1))



# calculate output of hidden layer 1

h1 = f(np.dot(W_h1, X) + b_h1)


h2 = f(np.dot(W_h2, h1) + b_h2)

display(h1.shape)
display(h2.shape)


(4, 100)

(3, 100)

## Gradient descent in Numpy:
Let us now start training a neural network
We start by implementing a simple gradient descent for linear regression

In [102]:

converged = False
iter = 0
m = 10 # Number of samples
ni= 1 # Number of input neurons
h = 1 # Number of hidden layers
no =1 # Number of neurons in the output layer

# Generate a random X (we do not have a real data)
X = np.random.rand(m)
display(X)

# learning rate
alpha =0.01

# early stop criteria 
ep=0.001

# maximum number of training iterations
max_iter=100

# Generate a random weights vector for the output layer
W1 = np.random.rand()

# Generate a random bias for the output layer 
b1 = np.random.rand()

# Generate a random ground truth
Y_gr = np.random.rand(m)


J = sum([(b1 + W1*X[i] - Y_gr[i])**2 for i in range(m)]) #cost function sum of squared error

while not converged:
        print('Interations:' , iter)
        
        # for each training sample, compute the gradient (d/d_theta j(theta))
        grad0 = 1.0/m * sum([(b1 + W1*X[i] - Y_gr[i]) for i in range(m)]) 
        grad1 = 1.0/m * sum([(b1 + W1*X[i] - Y_gr[i])*X[i] for i in range(m)])
        
        # update the theta_temp
        temp0 = b1 - alpha * grad0
        temp1 = W1 - alpha * grad1
        # update theta
        b1 = temp0
        W1 = temp1
        
        # sum squared error
        e = sum([(b1 + W1*X[i] - Y_gr[i])**2 for i in range(m)]) 
        print('Error:', e)

        if abs(J-e) <= ep:
            print('Converged, iterations: ', iter, '!!!')
            converged = True
    
        J = e   # update error 
        iter += 1  # update iter
    
        if iter == max_iter:
            print('Max interactions exceeded!')
            converged = True

array([0.65158367, 0.59275324, 0.55797387, 0.72800422, 0.06123583,
       0.45424021, 0.76800388, 0.38562263, 0.06658242, 0.1171803 ])

Interations: 0
Error: 1.6264258872181683
Interations: 1
Error: 1.6220444873792421
Interations: 2
Error: 1.6177586584947963
Interations: 3
Error: 1.613566124526418
Interations: 4
Error: 1.6094646638710521
Interations: 5
Error: 1.6054521080588349
Interations: 6
Error: 1.6015263404820725
Interations: 7
Error: 1.5976852951546243
Interations: 8
Error: 1.5939269555009647
Interations: 9
Error: 1.5902493531742137
Interations: 10
Error: 1.5866505669024404
Interations: 11
Error: 1.5831287213625655
Interations: 12
Error: 1.5796819860812006
Interations: 13
Error: 1.5763085743617846
Interations: 14
Error: 1.5730067422373806
Interations: 15
Error: 1.569774787448526
Interations: 16
Error: 1.5666110484455353
Interations: 17
Error: 1.563513903414663
Interations: 18
Error: 1.5604817693275734
Interations: 19
Error: 1.5575131010135383
Interations: 20
Error: 1.5546063902538316
Interations: 21
Error: 1.5517601648977948
Interations: 22
Error: 1.5489729880000358
Interations: 23
Error: 1.546243456978276
Intera

##Assignment 1
### Backpropagation in Numpy:
