# Lab on Machine Learning and Applications in Intelligent Vehicles
## Session 1: Introduction


### Course Plan:

This lab is a continuation to the Machine learning lecture, the objective of this course is to learn how to model and implement neural networks using deep learning python frameworks: 
1. Tensorflow
2. Keras
3. Pytorch

Useing these frameworks, we will go through the following topics and use cases:

#### Session 1: 05.06 - 09:00 - 11:00  :

>#### Presentation:  05.06 - 09:00 - 10:30:
>1. Introduction to deep learning frameworks
2. Deep learning in Numpy

>#### Break:  05.06 - 10:30 - 10:45
>#### Assignment:  05.06 - 10:45 - 11:45 : 
>* Implementation of backprop using numpy

>1. Tensorflow backround 
2. Implementation of feedforward neural networks using Tensorflow

>#### Break:  05.06 - 10:00 - 10:15
>#### Assignment:  05.06 - 10:15 - 10:45 : 
  
  >* play around with tensorflow and build your first neural network



#### Session 2:  05.06 - 11:00 - 12:00  :

>#### Presentation:  05.06 - 11:00 - 12:00:


>3. Implementation of CNN useing Tensorflow
4. Tensorboard

>#### Break:  05.06 - 12:00 - 13:00
>#### Assignment:  05.06 - 13:00 - 13:30 :


 #### Session 3:  05.06 - 13:30 - 15:00  :

>#### Presentation:  05.06 - 13:00 - 14:00:

>5. Introduction to Keras
6. CNN using Keras
>#### Break:  05.06 - 14:00 - 14:15
>#### Assignment:  05.06 - 14:15 - 14:45 :

 #### Session 4:  05.06 - 15:00 - 16:30  :

>#### Presentation:  05.06 - 15:00 - 15:45:

>7. LSTM using Keras

>#### Break:  05.06 - 15:45 - 16:00
>#### Assignment:  05.06 - 16:00 - 16:30 :


8. VGG, Inceptaion, ResNet models using Keras

9. Autoencoders using Keras

10. Sequence to Sequence Models using Keras 

11. Attention Mechanism using Keras
12. GANS 
13. Introduction to Pytorch
14. Machine translation using Pytorch
15. Introduction to Allennlp
16. Deep Reinforcment Learning using Keras
17. Use case: building self driving car using Unity and tensorflow










#Session 1: 05.06 - 09:00 - 11:00 :




## Deep learning frameworks:

In the past decade, many deep learning frameworks have been developed to ease and scale the research and development of AI. Many big technology providers including Google, IBM, Microsoft and Facebook have entered the race to provide the best and most popluar frameworks. To enter such a race, mainly four features are considered in the provided framework:

1. Uses a popular language for data scientists (Python, Scale, C++ or R)
2. Flexible in creating and adjusting deep learning architectures -> Functional programming
3. Easy for computing gradients
4. Interface with GPUs for parallel processing


In the following we see the most popular provided deep learning frameworks with their providers
https://towardsdatascience.com/deep-learning-framework-power-scores-2018-23607ddf297a

![alt text](https://cdn-images-1.medium.com/max/1600/1*dYjDEI0mLpsCOySKUuX1VA.png)

## Tensorflow
TensorFlow is the undisputed heavyweight champion. It has the most GitHub activity, Google searches, Medium articles, books on Amazon and ArXiv articles. It also has the most developers using it and is listed in the most online job descriptions. TensorFlow is backed by Google.

## Keras
Keras has an “API designed for human beings, not machines.” It is the second most popular framework in nearly all evaluation areas. Keras sits on top of TensorFlow, Theano, or CNTK. Start with Keras if you are new to deep learning.

## Pytorch

PyTorch is the third most popular overall framework and the second most popular stand-alone framework. It is younger than TensorFlow and has grown rapidly in popularity. It allows customization that TensorFlow does not. It has the backing of Facebook.

## Theano

Theano was developed at the University of Montreal in 2007 and is the oldest significant Python deep learning framework. It has lost much of its popularity and its leader stated that major releases were no longer on the roadmap. However, updates continue to be made. Theano still the fifth highest scoring framework.

# Comparision:

## Criteria 1: Online Job Listings

TensorFlow is the clear winner when it comes to frameworks mentioned in job listings. Learn it if you want a job doing deep learning.

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*kA8dIgRqLdWgKgs2sd7clA.png)

## Criteria 2: Usage


Keras showed a surprising amount of use — nearly as much as TensorFlow. It’s interesting that US employers are overwhelmingly looking for TensorFlow skills, when — at least internationally — Keras is used almost as frequently.

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*6b2Tm0oFr99zKaxkr4g52w.png)
  
  
## Criteria 4: Google Search Activity

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*wpA6C9x_Nri42EzbqnS1fQ.png)

## Criteria 5: Medium Articles

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*Y1cJUgZTC3u_hU1lmdsroQ.png)


## Criteria 6: Amazon Books

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*mtP47q29T6agdkEoJcCw-w.png)

## Criteria 7 : ArXiv Articles

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*7jdNoNkGlx_1EnfevQXRvw.png)
  
## Criteria 8: GitHub Activity

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*eOOYV3C5klsuVBMX31ngxw.png)
  
 --------------------------------
 


  
 








```
# This is formatted as code
```


Before we jump into Tensorflow, we will implemented our first neural network model using Python Numpy package. NumPy is the fundamental package for scientific computing with Python, such as:

1. Linear Algebra
2. Statistics
3. Calculus

## A brief intro to Numpy operations:

1. Creating a Vector:
Here we use Numpy to create a 1-D Array which we then call a vector.





In [0]:
import numpy as np

v1 = np.zeros((1,100))

v2 = np.zeros((1,100))

v2.T.shape

v3 = np.ones((1,100))
v4 = np.eye(4)

v5 = np.random.randn(10000,1) #normal distribution
v6 = np.random.rand(10000,1) #uniform distribution

display('mean of randn: ',v5.mean())
display('std of randn: ', v5.std())

display('mean of rand: ',v6.mean())
display('min of rand: ', v6.min())
display('max of rand: ', v6.max())

2. Creating a Matrix
We Create a 2-D Array in Numpy and call it a Matrix. It contains 2 rows and 3 columns.

In [35]:
m1 = np.zeros((2,3))
display(m1)


matrix = np.array([[1,2,3], [4,5,6]])
display(matrix)

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[1, 2, 3],
       [4, 5, 6]])

3. Selecting Elements


In [46]:
display(matrix[0,0]) #first row first col
display(matrix[0,-1]) #first row last col
display(matrix[0,-2])
display(matrix[0,1:]) #first row last two elements
display(matrix[0,:-1]) #first row first two elements
display(matrix[0,0:2]) #first row first two elements 
display(matrix[-1,0:2]) #last row first two elements


1

3

2

array([2, 3])

array([1, 2])

array([1, 2])

array([4, 5])

4. Describing a Matrix

In [48]:
#View the number of rows and columns
print(matrix.shape)
#View the number of elements (rows * columns)
print(matrix.size)
#View the number of dimensions (2 in this case)
print(matrix.ndim)

(2, 3)
6
2


5. Finding the max and min values

In [65]:
display(matrix)
matrix.min(axis=0)


np.min(matrix, axis=1)
np.max(matrix, axis=1)
display('arg',np.argmax(matrix, axis=0))
display('max',np.max(matrix, axis=0))
display('max',np.argmax(matrix))

np.argwhere(matrix==np.max(matrix))
np.argwhere(matrix<np.max(matrix))


array([[1, 2, 3],
       [4, 5, 6]])

'arg'

array([1, 1, 1])

'max'

array([4, 5, 6])

'max'

5

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 1]])

6. Reshaping Arrays


In [72]:
matrix.shape

matrix.reshape((3,2))
matrix.reshape((6,1))
matrix.reshape((1,6))
matrix.reshape((1,2,3)) #dim 0 size=1, dim 1 = 2, dim 2 = 3
matrix.reshape((1,-1,3)).shape

(1, 2, 3)

7. Calculating Dot Products

In [73]:
#Create vector-1
vector_1 = np.array([1,2,3])
#Create vector-2
vector_2 = np.array([4,5,6])

#Calculate Dot Product
print(np.dot(vector_1, vector_2))
#Alternatively you can use @ to calculate dot products
print(vector_1@vector_2)

32
32


##Linear regression in Numpy:

---



Write the numpy code for the following model:

$Y=WX+B$

where $X$ is 3x10 matrix:  10 samples and 3 features

$Y$ is 4x10 matrix: 10 samples and 4 outputs

$W$ is the weights matrix with the shape 4x3: connecting 3 inputs to 4 outputs

$b$ is a vector with a size 4 ( one bias per output)


In [82]:
#Input or feature matrix
X = np.random.rand(3,10)
display('Shape of X',X.shape)

#weight matrix
W = np.random.rand(4,3)

#bias
b = np.zeros((4,1))

#regression model
Y = np.dot(W, X)+b #4x3, 3x10 

display('Shape of Y:', Y.shape)


'Shape of X'

(3, 10)

'Shape of Y:'

(4, 10)

## One neuron model in numpy:

A single neuron has multiple inputs and one output, in addition to the linear regression model, we need to add non linearity through an activation function:

$Y= f(WX+B)$

where $X$ is n x m matrix:  m samples and n features/inputs

$f(g)= \frac{1}{1+\exp(-g)}$  is a sigmoid acitavation function

$Y$ is nh1 x m matrix: m samples and ny outputs

$W$ is the weights matrix with the shape nh1 x n: connecting 3 inputs to 4 outputs

$b$ is a vector with a size nh1 ( one bias per output)





In [0]:
#def f(x):
#  return 1.0/(1.0+np.exp(-x))

num_inputs = 3
num_outputs = 4
num_samples = 100

f = lambda x: 1.0/(1.0+np.exp(-x))

X=np.random.rand(num_inputs,num_samples)
W = np.random.rand(num_outputs,num_inputs)

b = np.random.rand(num_outputs,1)

Y = f(np.dot(W, X)+b)
display(Y)


## One hidden layer model in numpy:

The difference from the one neuron model is simple:  we need only to change the number of output "ny"

In [86]:
num_inputs = 3
num_outputs = 3
num_samples = 100
num_hidden_layer_1 = 4

f = lambda x: 1.0/(1.0+np.exp(-x))

X = np.random.rand(num_inputs,num_samples)
W1 = np.random.rand(num_hidden_layer_1,num_inputs)
W2 = np.random.rand(num_outputs, num_hidden_layer_1)

b1 = np.random.rand(num_hidden_layer_1, 1)
b2 = np.random.rand(num_outputs,1)


hidden1 = f(np.dot(W1, X)+b1)

Y = f(np.dot(W2, hidden1)+b2)
display(Y)


array([[0.89806891, 0.87147989, 0.8956725 , 0.89271881, 0.89697018,
        0.89622779, 0.90164432, 0.89705627, 0.89301138, 0.88934097,
        0.87289035, 0.89940254, 0.90241514, 0.89485507, 0.88651545,
        0.88868976, 0.89459682, 0.88895798, 0.89657316, 0.89331295,
        0.88889266, 0.89039188, 0.89031676, 0.89680258, 0.89028019,
        0.88449996, 0.89092268, 0.8859153 , 0.89790704, 0.88359024,
        0.90002277, 0.89983591, 0.89471185, 0.90087434, 0.90275699,
        0.87505486, 0.89216761, 0.90109452, 0.89818478, 0.89098762,
        0.89430788, 0.88645668, 0.90228657, 0.89243567, 0.8944335 ,
        0.88606005, 0.89573808, 0.88918279, 0.88964106, 0.88959536,
        0.88643863, 0.89148067, 0.89751406, 0.89024076, 0.89284754,
        0.87571477, 0.88485069, 0.89923404, 0.89577274, 0.89503881,
        0.89241213, 0.89378092, 0.90134497, 0.89336623, 0.89052165,
        0.88178197, 0.90219829, 0.89349339, 0.89254953, 0.8909212 ,
        0.8963549 , 0.89172975, 0.89465266, 0.89

## Gradient descent in Numpy:
Let us now start training a neural network
We start by implementing a simple gradient descent for linear regression

In [0]:
converged = False
iter = 0
m = 10 #number of samples
ni = 1 #number of input neurons
h = 1 #number of hidden layers
no = 1 #number of neurons in the ourput layer

#Generate a random X (we dont have real data)
X = np.random.rand(m)
display(X)

#learning rate
alpha = 0.01

#early stop criteria
ep = 0.001

#max number of training iterations
max_iter=1000

#Generate a random weights vector for the output layer
W1 = np.random.rand()

#Generate a random bias for the output layer 
b1 = np.random.rand()

#Generate a random ground truth
Y_gr = np.random.rand(m)

J = sum([(b1 + W1*X[i] - Y_gr[i])**2 for i in range(m)]) #cost function

while not converged:
  print('Iterations:', iter)
  #for each training sample, compute the gradient (d/D_theta j(theta))
  grad0 = 1.0/m * sum([(b1 + W1*X[i] - Y_gr[i]) for i in range(m)])
  grad1 = 1.0/m * sum([(b1 + W1*X[i] - Y_gr[i])*X[i] for i in range(m)])
  
  #update the theta_temp
  temp0 = b1 - alpha * grad0
  temp1 = W1 - alpha * grad1
  #update theta
  b1 = temp0
  W1 = temp1
  
  #sum suqared error
  e = sum([(b1 + W1*X[i] - Y_gr[i])**2 for i in range(m)])
  
  if abs(J-e)<= ep:
    print('Converged, iterations: ', iter, '!!!')
    converged=True
    
  J = e  #update error
  iter += 1 #update iter
  
  if iter == max_iter:
    print('Max iterations exceeded!')
    converged = True
    

##Assignment 1
### Backpropagation in Numpy:


In [105]:
# define the sigmoid function
def sigmoid(x, derivative=False):

    if (derivative == True):
        return x * (1 - x)
    else:
        return 1 / (1 + np.exp(-x))

# choose a random seed for reproducible results
np.random.seed(1)

# learning rate
alpha = .1

# number of nodes in the hidden layer
num_hidden = 3

# inputs
X = np.array([  
    [0, 0, 1],
    [0, 1, 1],
    [1, 0, 0],
    [1, 1, 0],
    [1, 0, 1],
    [1, 1, 1],
])

# outputs
# x.T is the transpose of x, making this a column vector
y = np.array([[0, 1, 0, 1, 1, 0]]).T

# initialize weights randomly with mean 0 and range [-1, 1]
# the +1 in the 1st dimension of the weight matrices is for the bias weight
hidden_weights = 2*np.random.random((X.shape[1] + 1, num_hidden)) - 1
output_weights = 2*np.random.random((num_hidden + 1, y.shape[1])) - 1

# number of iterations of gradient descent
num_iterations = 10000

# for each iteration of gradient descent
for i in range(num_iterations):

    # forward phase
    # np.hstack((np.ones(...), X) adds a fixed input of 1 for the bias weight
    input_layer_outputs = np.hstack((np.ones((X.shape[0], 1)), X))
    hidden_layer_outputs = np.hstack((np.ones((X.shape[0], 1)), sigmoid(np.dot(input_layer_outputs, hidden_weights))))
    output_layer_outputs = np.dot(hidden_layer_outputs, output_weights)

    # backward phase
    # output layer error term
    output_error = output_layer_outputs - y
    # hidden layer error term
    # [:, 1:] removes the bias term from the backpropagation
    hidden_error = hidden_layer_outputs[:, 1:] * (1 - hidden_layer_outputs[:, 1:]) * np.dot(output_error, output_weights.T[:, 1:])

    # partial derivatives
    hidden_pd = input_layer_outputs[:, :, np.newaxis] * hidden_error[: , np.newaxis, :]
    output_pd = hidden_layer_outputs[:, :, np.newaxis] * output_error[:, np.newaxis, :]

    # average for total gradients
    total_hidden_gradient = np.average(hidden_pd, axis=0)
    total_output_gradient = np.average(output_pd, axis=0)

    # update weights
    hidden_weights += - alpha * total_hidden_gradient
    output_weights += - alpha * total_output_gradient

# print the final outputs of the neural network on the inputs X
print("Output After Training: \n{}".format(output_layer_outputs))

Output After Training: 
[[2.11135662e-04]
 [9.99525588e-01]
 [1.66889680e-04]
 [9.99576185e-01]
 [9.99362960e-01]
 [1.30185107e-03]]
