# Lab on Machine Learning and Applications in Intelligent Vehicles
## Session 1: Introduction


In [2]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

In [1]:
!pip install -q matplotlib-venn

hello world


### Course Plan:

This lab is a continuation to the Machine learning lecture, the objective of this course is to learn how to model and implement neural networks using deep learning python frameworks: 
1. Tensorflow
2. Keras
3. Pytorch

Useing these frameworks, we will go through the following topics and use cases:

#### Session 1: 05.06 - 09:00 - 11:00  :

>#### Presentation:  05.06 - 09:00 - 10:30:
>1. Introduction to deep learning frameworks
2. Deep learning in Numpy

>#### Break:  05.06 - 10:30 - 10:45
>#### Assignment:  05.06 - 10:45 - 11:45 : 
>* Implementation of backprop using numpy

>1. Tensorflow backround 
2. Implementation of feedforward neural networks using Tensorflow

>#### Break:  05.06 - 10:00 - 10:15
>#### Assignment:  05.06 - 10:15 - 10:45 : 
  
  >* play around with tensorflow and build your first neural network



#### Session 2:  05.06 - 11:00 - 12:00  :

>#### Presentation:  05.06 - 11:00 - 12:00:


>3. Implementation of CNN useing Tensorflow
4. Tensorboard

>#### Break:  05.06 - 12:00 - 13:00
>#### Assignment:  05.06 - 13:00 - 13:30 :


 #### Session 3:  05.06 - 13:30 - 15:00  :

>#### Presentation:  05.06 - 13:00 - 14:00:

>5. Introduction to Keras
6. CNN using Keras
>#### Break:  05.06 - 14:00 - 14:15
>#### Assignment:  05.06 - 14:15 - 14:45 :

 #### Session 4:  05.06 - 15:00 - 16:30  :

>#### Presentation:  05.06 - 15:00 - 15:45:

>7. LSTM using Keras

>#### Break:  05.06 - 15:45 - 16:00
>#### Assignment:  05.06 - 16:00 - 16:30 :


8. VGG, Inceptaion, ResNet models using Keras

9. Autoencoders using Keras

10. Sequence to Sequence Models using Keras 

11. Attention Mechanism using Keras
12. GANS 
13. Introduction to Pytorch
14. Machine translation using Pytorch
15. Introduction to Allennlp
16. Deep Reinforcment Learning using Keras
17. Use case: building self driving car using Unity and tensorflow










#Session 1: 05.06 - 09:00 - 11:00 :




## Deep learning frameworks:

In the past decade, many deep learning frameworks have been developed to ease and scale the research and development of AI. Many big technology providers including Google, IBM, Microsoft and Facebook have entered the race to provide the best and most popluar frameworks. To enter such a race, mainly four features are considered in the provided framework:

1. Uses a popular language for data scientists (Python, Scale, C++ or R)
2. Flexible in creating and adjusting deep learning architectures -> Functional programming
3. Easy for computing gradients
4. Interface with GPUs for parallel processing


In the following we see the most popular provided deep learning frameworks with their providers
https://towardsdatascience.com/deep-learning-framework-power-scores-2018-23607ddf297a

![alt text](https://cdn-images-1.medium.com/max/1600/1*dYjDEI0mLpsCOySKUuX1VA.png)

## Tensorflow
TensorFlow is the undisputed heavyweight champion. It has the most GitHub activity, Google searches, Medium articles, books on Amazon and ArXiv articles. It also has the most developers using it and is listed in the most online job descriptions. TensorFlow is backed by Google.

## Keras
Keras has an “API designed for human beings, not machines.” It is the second most popular framework in nearly all evaluation areas. Keras sits on top of TensorFlow, Theano, or CNTK. Start with Keras if you are new to deep learning.

## Pytorch

PyTorch is the third most popular overall framework and the second most popular stand-alone framework. It is younger than TensorFlow and has grown rapidly in popularity. It allows customization that TensorFlow does not. It has the backing of Facebook.

## Theano

Theano was developed at the University of Montreal in 2007 and is the oldest significant Python deep learning framework. It has lost much of its popularity and its leader stated that major releases were no longer on the roadmap. However, updates continue to be made. Theano still the fifth highest scoring framework.

# Comparision:

## Criteria 1: Online Job Listings

TensorFlow is the clear winner when it comes to frameworks mentioned in job listings. Learn it if you want a job doing deep learning.

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*kA8dIgRqLdWgKgs2sd7clA.png)

## Criteria 2: Usage


Keras showed a surprising amount of use — nearly as much as TensorFlow. It’s interesting that US employers are overwhelmingly looking for TensorFlow skills, when — at least internationally — Keras is used almost as frequently.

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*6b2Tm0oFr99zKaxkr4g52w.png)
  
  
## Criteria 4: Google Search Activity

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*wpA6C9x_Nri42EzbqnS1fQ.png)

## Criteria 5: Medium Articles

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*Y1cJUgZTC3u_hU1lmdsroQ.png)


## Criteria 6: Amazon Books

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*mtP47q29T6agdkEoJcCw-w.png)

## Criteria 7 : ArXiv Articles

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*7jdNoNkGlx_1EnfevQXRvw.png)
  
## Criteria 8: GitHub Activity

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*eOOYV3C5klsuVBMX31ngxw.png)
  
 --------------------------------
 


  
 








```
# This is formatted as code
```


Before we jump into Tensorflow, we will implemented our first neural network model using Python Numpy package. NumPy is the fundamental package for scientific computing with Python, such as:

1. Linear Algebra
2. Statistics
3. Calculus

## A brief intro to Numpy operations:

1. Creating a Vector:
Here we use Numpy to create a 1-D Array which we then call a vector.





In [11]:
import numpy as np

v1=np.zeros((1,100))
display(v1)
v2=np.zeros((1,100))
display(v2)

v2.shape
v2.T.shape

v3=np.ones((1,100))#vetor mit einensen 
v4=np.eye(4) #einheits vector
display(v4)

v5 = np.random.randn(100,1) #normal random gernerator
v6 = np.random.rand(100,1) #uniform random gernerator
display('mean of rand:',v5)
display('std of rand:',v6)
display('min of rand:',v6.min())
display('max of rand:',v6.max())

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

'mean of rand:'

array([[-7.31875805e-01],
       [-1.17175846e+00],
       [ 8.03180519e-01],
       [-4.13209430e-01],
       [-2.68628408e+00],
       [-9.70714391e-01],
       [ 1.81097729e+00],
       [ 6.20278972e-01],
       [ 2.18111213e-01],
       [ 7.07010460e-01],
       [-1.01857879e+00],
       [-8.35232646e-01],
       [ 1.02995062e+00],
       [-3.48170361e-01],
       [-4.37566758e-01],
       [-1.71824104e-01],
       [-2.96760354e-01],
       [-9.95395447e-01],
       [ 2.40336283e-01],
       [ 9.48468289e-01],
       [-1.07044856e+00],
       [ 2.04320789e-02],
       [-5.97495501e-01],
       [ 1.82972015e+00],
       [-1.44100388e+00],
       [ 2.46800145e-01],
       [-7.49981071e-01],
       [-3.57214714e-01],
       [ 8.52329193e-01],
       [ 4.76212740e-01],
       [-6.13518942e-01],
       [-3.11600631e-01],
       [-7.48632916e-01],
       [ 2.69648933e+00],
       [ 6.25211315e-01],
       [-3.07978194e-01],
       [-9.84716248e-01],
       [-5.60065625e-01],
       [ 1.0

'std of rand:'

array([[0.72671586],
       [0.35247068],
       [0.19876316],
       [0.48526913],
       [0.17320491],
       [0.80226554],
       [0.3731047 ],
       [0.6409606 ],
       [0.27606342],
       [0.62096069],
       [0.93169577],
       [0.75336855],
       [0.77711228],
       [0.33771268],
       [0.20756868],
       [0.36729765],
       [0.92306109],
       [0.81359478],
       [0.82635829],
       [0.03902532],
       [0.0260382 ],
       [0.63995629],
       [0.13096724],
       [0.55527685],
       [0.04331447],
       [0.40091884],
       [0.10936632],
       [0.37472292],
       [0.47274837],
       [0.56965319],
       [0.71256692],
       [0.74933072],
       [0.78121261],
       [0.05537198],
       [0.79127293],
       [0.14189234],
       [0.54779827],
       [0.86537924],
       [0.9282089 ],
       [0.82877626],
       [0.79643538],
       [0.51130499],
       [0.61575527],
       [0.83546622],
       [0.03616605],
       [0.82016173],
       [0.65350794],
       [0.174

'min of rand:'

0.024446406693232614

'max of rand:'

0.951101298044185

2. Creating a Matrix
We Create a 2-D Array in Numpy and call it a Matrix. It contains 2 rows and 3 columns.

3. Selecting Elements


4. Describing a Matrix

5. Finding the max and min values

6. Reshaping Arrays


7. Calculating Dot Products

##Linear regression in Numpy:

---



Write the numpy code for the following model:

$Y=WX+B$

where $X$ is 3x10 matrix:  10 samples and 3 features

$Y$ is 4x10 matrix: 10 samples and 4 outputs

$W$ is the weights matrix with the shape 4x3: connecting 3 inputs to 4 outputs

$b$ is a vector with a size 4 ( one bias per output)


## One neuron model in numpy:

A single neuron has multiple inputs and one output, in addition to the linear regression model, we need to add non linearity through an activation function:

$Y= f(WX+B)$

where $X$ is n x m matrix:  m samples and n features/inputs

$f(g)= \frac{1}{1+\exp(-g)}$  is a sigmoid acitavation function

$Y$ is nh1 x m matrix: m samples and ny outputs

$W$ is the weights matrix with the shape nh1 x n: connecting 3 inputs to 4 outputs

$b$ is a vector with a size nh1 ( one bias per output)





## One hidden layer model in numpy:

The difference from the one neuron model is simple:  we need only to change the number of output "ny"

## Gradient descent in Numpy:
Let us now start training a neural network
We start by implementing a simple gradient descent for linear regression

##Assignment 1
### Backpropagation in Numpy:
