test

In [2]:
import tensorflow
print('hello world')

hello world


In [0]:
!pip install -q matplotlib-venn

In [0]:
!apt-get -qq install -y libfluidsynth1

In [4]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

comments by Mareike [05.06.2019]

this course is about practical coding, how to use tensorflow etc, we will not go into theory

80% of the research papers use tensorflow

# Lab on Machine Learning and Applications in Intelligent Vehicles
## Session 1: Introduction


### Course Plan:

This lab is a continuation to the Machine learning lecture, the objective of this course is to learn how to model and implement neural networks using deep learning python frameworks: 
1. Tensorflow
2. Keras
3. Pytorch

Useing these frameworks, we will go through the following topics and use cases:

#### Session 1: 05.06 - 09:00 - 11:00  :

>#### Presentation:  05.06 - 09:00 - 10:30:
>1. Introduction to deep learning frameworks
2. Deep learning in Numpy

>#### Break:  05.06 - 10:30 - 10:45
>#### Assignment:  05.06 - 10:45 - 11:45 : 
>* Implementation of backprop using numpy

>1. Tensorflow backround 
2. Implementation of feedforward neural networks using Tensorflow

>#### Break:  05.06 - 10:00 - 10:15
>#### Assignment:  05.06 - 10:15 - 10:45 : 
  
  >* play around with tensorflow and build your first neural network



#### Session 2:  05.06 - 11:00 - 12:00  :

>#### Presentation:  05.06 - 11:00 - 12:00:


>3. Implementation of CNN useing Tensorflow
4. Tensorboard

>#### Break:  05.06 - 12:00 - 13:00
>#### Assignment:  05.06 - 13:00 - 13:30 :


 #### Session 3:  05.06 - 13:30 - 15:00  :

>#### Presentation:  05.06 - 13:00 - 14:00:

>5. Introduction to Keras
6. CNN using Keras
>#### Break:  05.06 - 14:00 - 14:15
>#### Assignment:  05.06 - 14:15 - 14:45 :

 #### Session 4:  05.06 - 15:00 - 16:30  :

>#### Presentation:  05.06 - 15:00 - 15:45:

>7. LSTM using Keras

>#### Break:  05.06 - 15:45 - 16:00
>#### Assignment:  05.06 - 16:00 - 16:30 :


8. VGG, Inceptaion, ResNet models using Keras

9. Autoencoders using Keras

10. Sequence to Sequence Models using Keras 

11. Attention Mechanism using Keras
12. GANS 
13. Introduction to Pytorch
14. Machine translation using Pytorch
15. Introduction to Allennlp
16. Deep Reinforcment Learning using Keras
17. Use case: building self driving car using Unity and tensorflow
[Note Mareike: we will not use Unity, but PGame (Phython based), because Unity is too heavy on your laptop]










#Session 1: 05.06 - 09:00 - 11:00 :




## Deep learning frameworks:

In the past decade, many deep learning frameworks have been developed to ease and scale the research and development of AI. Many big technology providers including Google, IBM, Microsoft and Facebook have entered the race to provide the best and most popluar frameworks. To enter such a race, mainly four features are considered in the provided framework:

1. Uses a popular language for data scientists (Python, Scale, C++ or R)
2. Flexible in creating and adjusting deep learning architectures -> Functional programming
3. Easy for computing gradients
4. Interface with GPUs for parallel processing


In the following we see the most popular provided deep learning frameworks with their providers
https://towardsdatascience.com/deep-learning-framework-power-scores-2018-23607ddf297a

![alt text](https://cdn-images-1.medium.com/max/1600/1*dYjDEI0mLpsCOySKUuX1VA.png)

## Tensorflow
TensorFlow is the undisputed heavyweight champion. It has the most GitHub activity, Google searches, Medium articles, books on Amazon and ArXiv articles. It also has the most developers using it and is listed in the most online job descriptions. TensorFlow is backed by Google.

## Keras
Keras has an “API designed for human beings, not machines.” It is the second most popular framework in nearly all evaluation areas. Keras sits on top of TensorFlow, Theano, or CNTK. Start with Keras if you are new to deep learning.

## Pytorch

PyTorch is the third most popular overall framework and the second most popular stand-alone framework. It is younger than TensorFlow and has grown rapidly in popularity. It allows customization that TensorFlow does not. It has the backing of Facebook.

## Theano

Theano was developed at the University of Montreal in 2007 and is the oldest significant Python deep learning framework. It has lost much of its popularity and its leader stated that major releases were no longer on the roadmap. However, updates continue to be made. Theano still the fifth highest scoring framework.

# Comparision:

## Criteria 1: Online Job Listings

TensorFlow is the clear winner when it comes to frameworks mentioned in job listings. Learn it if you want a job doing deep learning.

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*kA8dIgRqLdWgKgs2sd7clA.png)

## Criteria 2: Usage


Keras showed a surprising amount of use — nearly as much as TensorFlow. It’s interesting that US employers are overwhelmingly looking for TensorFlow skills, when — at least internationally — Keras is used almost as frequently.

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*6b2Tm0oFr99zKaxkr4g52w.png)
  
  
## Criteria 4: Google Search Activity

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*wpA6C9x_Nri42EzbqnS1fQ.png)

## Criteria 5: Medium Articles

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*Y1cJUgZTC3u_hU1lmdsroQ.png)


## Criteria 6: Amazon Books

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*mtP47q29T6agdkEoJcCw-w.png)

## Criteria 7 : ArXiv Articles

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*7jdNoNkGlx_1EnfevQXRvw.png)
  
## Criteria 8: GitHub Activity

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*eOOYV3C5klsuVBMX31ngxw.png)
  
 --------------------------------
 


  
 








```
# This is formatted as code
```


Before we jump into Tensorflow, we will implemented our first neural network model using Python Numpy package. NumPy is the fundamental package for scientific computing with Python, such as:

1. Linear Algebra
2. Statistics
3. Calculus

## A brief intro to Numpy operations:

1. Creating a Vector:
Here we use Numpy to create a 1-D Array which we then call a vector.





In [0]:
import numpy as np

v1 = np.zeros((1,100)) # 1 row, 100 columns
display(v1) # display v1 (in this case it will only show you the last number in this cell)
v2 = np.zeros((1,100))
display(v2)

v2.shape

v2.T.shape

v3 = np.ones((1,100)) # vector filled with ones
display(v3)

v4 = np.eye(4)
display(v4)

v5 = np.random.randn(100,1) # normal random generator with meand 0 and std 1 # if you put random, you don't need the inner brackets 
display(v5)
display('mean of randn:', v5.mean())
display('std of randn:', v5.std())

v6 = np.random.rand(100,1) # uniform random generator between 0 and 1
display('min of rand:', v6.min())
display('max of rand:', v6.max())

# right side dots: "clear output"

2. Creating a Matrix
We Create a 2-D Array in Numpy and call it a Matrix. It contains 2 rows and 3 columns.

In [27]:
m1 = np.zeros((2,3))
display(m1)

matrix = np.array([[1,2,3],[4,5,6]])
display('matrix:', matrix)
display('matrix shape:', matrix.shape)

array([[0., 0., 0.],
       [0., 0., 0.]])

'matrix:'

array([[1, 2, 3],
       [4, 5, 6]])

'matrix shape:'

(2, 3)

3. Selecting Elements


In [33]:
# select elemts from the matrix, indexing
display(matrix[0,0]) # first row, first column
display(matrix[0,-1]) # first row, last column -> last element in that dimension is -1
display(matrix[0,-2]) # first row, second last column
display(matrix[0,1:]) # start from the column 1 which will be considered, to the end
display(matrix[0,:-1]) # from the beginning, to the column before the last one (from col 0 - col 1)
display(matrix[0,0:2]) 
display(matrix[-1,0:2]) # you can do the same with rows of course

1

3

2

array([2, 3])

array([1, 2])

array([1, 2])

array([4, 5])

4. Describing a Matrix

In [34]:
# view the number of rows and columns
print(matrix.shape)
# view the number of elements (rows*columns)
print(matrix.size)
# view the number of dimensions (2 in this case)
print(matrix.ndim)

(2, 3)
6
2


5. Finding the max and min values

In [45]:
display(matrix)
matrix.min() # finding the minimum value in the whole matrix
matrix.min(axis=0) # finding the minimum in the first dimension (in the first row) (?) or finding the row that the minimum is in?

np.min(matrix, axis=1)
np.max(matrix, axis=1)
display('arm', np.argmax(matrix, axis=0)) # give the index of the value, not the value itself -> they are all in the first row
display('max', np.max(matrix, axis=0))
display('max', np.argmax(matrix)) # if I don't specify the axis, it should give me the column and row -> no there seems to be a standard (?)

np.argwhere(matrix == np.max(matrix)) # where is the matrix equal to the max
np.argwhere(matrix < np.max(matrix))
#np.where(matrix < np.max(matrix)) # values instead of indexes (?)

array([[1, 2, 3],
       [4, 5, 6]])

'arm'

array([1, 1, 1])

'max'

array([4, 5, 6])

'max'

5

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 1]])

6. Reshaping Arrays


In [51]:
matrix.shape
matrix.reshape((3,2)) # new shape -> the total size is not changed, means the elements should not change
matrix.reshape((6,1))
matrix.reshape((1,6))
matrix.reshape((1,2,3)) # dim 0 size = 1, dim 1 = 2, dim 2 = 3
matrix.reshape((1,-1,3)) # do it mathematically by putting -1
matrix.reshape((1,-1,3)).shape

#always just the last command is displayed!

(1, 2, 3)

7. Calculating Dot Products

In [52]:
# create vector-1
vector_1 = np.array([1,2,3])
# create vector-2
vector_2 = np.array([4,5,6])

# calculate dot product
print(np.dot(vector_1,vector_2))
# alternatively you can use @ to calculate dot products
print(vector_1 @ vector_2)

32
32


##Linear regression in Numpy:

---



Write the numpy code for the following model:

$Y=WX+B$

where $X$ is 3x10 matrix:  10 samples and 3 features

$Y$ is 4x10 matrix: 10 samples and 4 outputs

$W$ is the weights matrix with the shape 4x3: connecting 3 inputs to 4 outputs

$b$ is a vector with a size 4 ( one bias per output)


In [54]:
# for example in the lecture we had the correlation between house price and hozse size (linear regression modeling) [see lecture slides]

# samples is the number of trading(?) points

# we do not only want to predict the house price, but also 3 other values (?)
# x is the number of inputs I have, and Y is the number of outputs I want to have -> 3 inouts to 4 outputs
# linear equation -> one bias for each output



#inputs of featured matrix
X = np.random.rand(3,10) # initializing X
display('shape of X', X.shape)

#weights matrix
W = np.random.rand(4,3)

# b = np.zeros(4,) # when you put it like this, it doesn't have a first dimension, it only as one dimension, it's a vector, not a matrix -> 1 column with 4 elements
b = np.zeros((4,1))

#regression model
Y = np.dot(W,X) + b # 4x3, 3x10 (the "3" matches in both matrixes, which is required for the dot product)

display('Y:', Y.shape)


'shape of X'

(3, 10)

'Y:'

(4, 10)

## One neuron model in numpy:

A single neuron has multiple inputs and one output, in addition to the linear regression model, we need to add non linearity through an activation function:

$Y= f(WX+B)$

where $X$ is n x m matrix:  m samples and n features/inputs

$f(g)= \frac{1}{1+\exp(-g)}$  is a sigmoid acitavation function

$Y$ is nh1 x m matrix: m samples and ny outputs

$W$ is the weights matrix with the shape nh1 x n: connecting 3 inputs to 4 outputs

$b$ is a vector with a size nh1 ( one bias per output)





In [66]:
# first it's the same: we have the linear regression model
# sigmoid activation function




num_inputs = 3
num_outputs = 4 # change from 4 to 1
num_samples = 100

#def f(x):
#  return 1.0/(1.0 + np.exp(-x))

f = lambda x: 1.0/(1.0 + np.exp(-x)) # activation function (use sigmoid) #(if the function is small, you can write it in one line, like this)

#X = np.random.rand(3,10)
X = np.random.rand(num_inputs,num_samples)

#generate a random weights vector
#W = np.random.rand(1,3)
W = np.random.rand(num_outputs,num_inputs)

#generate a random bias
#b = np.random.rand()
b = np.random.rand(num_outputs,1)

#calculate Y
Y = f(np.dot(W,X) + b)
display(Y)
display(Y.shape)


array([[0.78858995, 0.8725482 , 0.75599497, 0.86911053, 0.81780511,
        0.9099843 , 0.88217435, 0.88401411, 0.90823638, 0.86117392,
        0.87498061, 0.8492863 , 0.84038455, 0.8606616 , 0.87048897,
        0.85903777, 0.80053258, 0.92193085, 0.79554629, 0.73023032,
        0.83890156, 0.86462991, 0.88058742, 0.85177217, 0.85946271,
        0.89845201, 0.91182342, 0.87138009, 0.85031561, 0.84787452,
        0.85752325, 0.86204343, 0.8765339 , 0.87865999, 0.85472268,
        0.87099022, 0.86627246, 0.88591829, 0.78794028, 0.84222458,
        0.81113267, 0.88716536, 0.86602093, 0.88581279, 0.86557437,
        0.88706605, 0.79909032, 0.83451945, 0.81595542, 0.87745031,
        0.87499609, 0.84783934, 0.8386781 , 0.88095891, 0.85630173,
        0.89389824, 0.80572607, 0.9178844 , 0.83181749, 0.83174387,
        0.85984243, 0.85314103, 0.8421249 , 0.8825569 , 0.80422448,
        0.85638786, 0.90700462, 0.85324681, 0.79130443, 0.85288183,
        0.89895171, 0.8423488 , 0.85338031, 0.88

(4, 100)

## Two hidden layer model in numpy:

The difference from the one neuron model is simple:  we need only to change the number of output "ny"

In [60]:
num_inputs = 3
hidden_layer_1_outputs = 4
hidden_layer_2_outputs = 3
num_samples = 100


f = lambda x: 1.0/(1.0 + np.exp(-x)) # activation function (use sigmoid)

X = np.random.rand(num_inputs,num_samples)

#generate a random weights vector for the first hidden layer
W_h1 = np.random.rand(hidden_layer_1_outputs,num_inputs)
#generate a random weights vector for the second hidden layer
W_h2 = np.random.rand(hidden_layer_2_outputs,num_inputs)

#generate a random bias for layer 1
b_h1 = np.random.rand(hidden_layer_1_outputs,1)
#generate a random bias for layer 2
b_h2 = np.random.rand(hidden_layer_2_outputs,1)

#calculate output of hidden layer 1
h1 = f(np.dot(W_h1,X) + b_h1)
display(h1.shape)
#[Note Mareike: take that output and put it into the inout for the second layer to get the final output]
#calculate output of hidden layer 2
h2 = f(np.dot(W_h2,X) + b_h2)
display(h2.shape)

(4, 100)

(3, 100)

## Gradient descent in Numpy:
Let us now start training a neural network
We start by implementing a simple gradient descent for linear regression

In [81]:
#THIS IS THE SOLUTION FROM HAJ MOSA!

import numpy as np
converged = False
iter = 0
m = 10 # Number of samples
ni= 1 # Number of input neurons
h = 1 # Number of hidden layers
no =1 # Number of neurons in the output layer

# Generate a random X (we do not have a real data)
X = np.random.rand(m)
display(X)

# learning rate
alpha =0.01

# early stop criteria 
ep=0.001

# maximum number of training iterations
max_iter=100

# Generate a random weights vector for the output layer
W1 = np.random.rand()

# Generate a random bias for the output layer 
b1 = np.random.rand()

# Generate a random ground truth
Y_gr = np.random.rand(m)


J = sum([(b1 + W1*X[i] - Y_gr[i])**2 for i in range(m)])

while not converged:
        # for each training sample, compute the gradient (d/d_theta j(theta))
        grad0 = 1.0/m * sum([(b1 + W1*X[i] - Y_gr[i]) for i in range(m)]) 
        grad1 = 1.0/m * sum([(b1 + W1*X[i] - Y_gr[i])*X[i] for i in range(m)])
        
        # update the theta_temp
        temp0 = W1 - alpha * grad0
        temp1 = b1 - alpha * grad1
        # update theta
        W1 = temp0
        b1 = temp1
        
        # sum squared error
        e = sum([(b1 + W1*X[i] - Y_gr[i])**2 for i in range(m)]) 

        if abs(J-e) <= ep:
            print('Converged, iterations: ', iter, '!!!')
            converged = True
    
        J = e   # update error 
        iter += 1  # update iter
    
        if iter == max_iter:
            print('Max interactions exceeded!')
            converged = True

array([0.40239252, 0.90468616, 0.03706105, 0.77387434, 0.12564138,
       0.61851357, 0.01036426, 0.53862728, 0.00301796, 0.95119379])

Max interactions exceeded!


##Assignment 1
### Backpropagation in Numpy:


In [80]:
#THIS IS THE SOLUTION FROM HAJ MOSA, BUT IT IS NOT CORRECT, BECAUSE THE COSTS ARE GOING UP AGAIN [Note Mareike, 05.06.2019, 14:!4 Uhr]

# [Note Mareike: we multiply the output and the cost to get the gradient]
    
num_inputs = 4
hidden_layer_1_outputs = 4
hidden_layer_2_outputs = 3

num_samples = 10

f = lambda x: 1.0/(1.0 + np.exp(-x)) # activation function (use sigmoid)


X = np.random.rand(num_samples,num_inputs-1) # 10x4

X = np.hstack((np.ones((X.shape[0], 1)), X))

display(X.shape)

# Generate a random weights vector for the first hidden layer
W_h1 = np.random.rand(num_inputs,hidden_layer_1_outputs) # 4x4

# Generate a random weights vector for the second hidden layer
W_h2 = np.random.rand(hidden_layer_1_outputs+1,hidden_layer_2_outputs)




# Calculate output of hidden layer 1
h1= f(np.dot(X,W_h1))
display(h1.shape)

# Calculate output of hidden layer 2
#h2= f(np.dot(h1,W_h2))
#display(h2.shape)


# learning rate
alpha =0.01

# early stop criteria 
ep=0.001

# maximum number of training iterations
max_iter=100

# Generate a random ground truth
Y_gr = np.random.rand(hidden_layer_2_outputs,num_samples)

#J = sum([(h2 - Y_gr[:,i])**2 for i in range(num_samples)]) #cost function sum of squared error
print(J)

#while not converged:
for i in range(100):
        #print('Interations:' , iter)
    
        # forward prop   
        # Calculate output of hidden layer 1
        h1= f(np.dot(X,W_h1))
        
        # append a column with ones representing bias inputs
        h1 = np.hstack((np.ones((h1.shape[0], 1)), h1))
        # Calculate output of hidden layer 2
        h2= f(np.dot(h1,W_h2))
        
        
        #error/error 
               
        J = np.sum(np.square(h2- Y_gr.T))
        
        # gradient of the output layer
        grad_h2 = h2*J
        
       
      
        
        # error
        
        #display('h1', (h1[:, 1:] * (1 - h1[:, 1:])).shape)
        
        
        #display('dot ', np.dot(grad_h2, W_h2.T[:, 1:]).shape)
        
        hidden_error = (h1[:, 1:] * (1 - h1[:, 1:])) * np.dot(grad_h2, W_h2.T[:, 1:]) 

        #print(h1.shape)
        #print(hidden_error.shape)
        grad_h1= h1[:, :, np.newaxis]*hidden_error[:, np.newaxis, :]

      
        # average gradient
        total_hidden_gradient_h2 = np.average(grad_h2, axis=0)
        total_output_gradient_h1 = np.average(grad_h1, axis=0)
        #print(grad_h1.shape)
        #print(W_h1.shape)

        # update weights
        W_h2 += - alpha * total_hidden_gradient_h2
        W_h1 += - alpha * total_output_gradient_h1[1:,:]
        
        
        print('iter',i)
        
        print('cost',J)
        
# you can see that the cost is decreasing, so the gradient is correct and working
        
        

(10, 4)

(10, 4)

1.1066192646170356
iter 0
cost 8.075351789038114
iter 1
cost 7.439741107832017
iter 2
cost 6.839658882245434
iter 3
cost 6.286284903616905
iter 4
cost 5.7856626574918595
iter 5
cost 5.340043265937991
iter 6
cost 4.948692870822416
iter 7
cost 4.608712765165367
iter 8
cost 4.315883744662298
iter 9
cost 4.0653930827915445
iter 10
cost 3.852362119763957
iter 11
cost 3.6721743409043173
iter 12
cost 3.520646195521173
iter 13
cost 3.3940910434007487
iter 14
cost 3.2893184525514374
iter 15
cost 3.2035988584002673
iter 16
cost 3.1346127921994156
iter 17
cost 3.0803959785311443
iter 18
cost 3.0392863876898497
iter 19
cost 3.0098761313260303
iter 20
cost 2.9909692474387475
iter 21
cost 2.981545429219222
iter 22
cost 2.980729268049515
iter 23
cost 2.9877643854465066
iter 24
cost 3.001991788819797
iter 25
cost 3.0228318235116327
iter 26
cost 3.049769164507568
iter 27
cost 3.082340371446587
iter 28
cost 3.120123607842755
iter 29
cost 3.1627301941120574
iter 30
cost 3.2097977220733744
iter 31
cost 3.

###The Backpropagation Code
from the lecture slides session 4 (not actual part of this/todays class)

In [0]:
# define the sigmoid function
def sigmoid(x, derivative=False):
    
    f=1 / (1 + np.exp(-x))

    if (derivative == True):
        return f * (1 - f)
    else:
        return f

In [0]:
np.random.seed(1)

# learning rate
rho = .001

# number of nodes in the hidden layer
num_hidden = 3

# inputs
X = np.array([  
    [0, 0, 1],
    [0, 1, 1],
    [1, 0, 0],
    [1, 1, 0],
    [1, 0, 1],
    [1, 1, 1],
])

# outputs
# x.T is the transpose of x, making this a column vector
y = np.array([[0, 1, 0, 1, 1, 0]]).T

In [0]:
hidden_weights = 2*np.random.random((X.shape[1] + 1, num_hidden)) - 1
output_weights = 2*np.random.random((num_hidden + 1, y.shape[1])) - 1

In [70]:
X.shape

(6, 3)

In [71]:
y.shape

(6, 1)

In [72]:
hidden_weights.shape

(4, 3)

In [73]:
hidden_weights

array([[-0.16595599,  0.44064899, -0.99977125],
       [-0.39533485, -0.70648822, -0.81532281],
       [-0.62747958, -0.30887855, -0.20646505],
       [ 0.07763347, -0.16161097,  0.370439  ]])

In [74]:
output_weights

array([[-0.5910955 ],
       [ 0.75623487],
       [-0.94522481],
       [ 0.34093502]])

In [0]:
num_iterations = 10000

In [0]:
    # forward phase
    # np.hstack((np.ones(...), X) adds a fixed input of 1 for the bias weight
input_layer_outputs = np.hstack((np.ones((X.shape[0], 1)), X))
a=sigmoid(np.dot(input_layer_outputs, hidden_weights))
hidden_layer_outputs = np.hstack((np.ones((X.shape[0], 1)), a))
output_layer_outputs = np.dot(hidden_layer_outputs, output_weights)
    
output_error = y-output_layer_outputs
    # hidden layer error term
    # [:, 1:] removes the bias term from the backpropagation
    
    #hidden_layer_outputs[:, 1:] is f(z) is sigmoid(x) 
    #hidden_layer_outputs[:, 1:] * (1 - hidden_layer_outputs[:, 1:]) = f(z)(1-f(z))
    #np.dot(output_error, output_weights.T[:, 1:]) slide number 11
    
hidden_error = hidden_layer_outputs[:, 1:] * (1 - hidden_layer_outputs[:, 1:]) * np.dot(output_error, output_weights.T[:, 1:])

    
        # partial derivatives
hidden_pd = input_layer_outputs[:, :, np.newaxis] * hidden_error[: , np.newaxis, :]
output_pd = hidden_layer_outputs[:, :, np.newaxis] * output_error[:, np.newaxis, :]

In [77]:
output_error.shape

(6, 1)

In [78]:
for i in range(num_iterations):

    # forward phase
    # np.hstack((np.ones(...), X) adds a fixed input of 1 for the bias weight
    input_layer_outputs = np.hstack((np.ones((X.shape[0], 1)), X))
    a=sigmoid(np.dot(input_layer_outputs, hidden_weights))
    hidden_layer_outputs = np.hstack((np.ones((X.shape[0], 1)), a))
    output_layer_outputs = np.dot(hidden_layer_outputs, output_weights)
    
    output_error = y-output_layer_outputs
    # hidden layer error term
    # [:, 1:] removes the bias term from the backpropagation
    
    #hidden_layer_outputs[:, 1:] is f(z) is sigmoid(x) 
    #hidden_layer_outputs[:, 1:] * (1 - hidden_layer_outputs[:, 1:]) = f(z)(1-f(z))
    #np.dot(output_error, output_weights.T[:, 1:]) slide number 11
    
    hidden_error = hidden_layer_outputs[:, 1:] * (1 - hidden_layer_outputs[:, 1:]) * np.dot(output_error, output_weights.T[:, 1:])

    
        # partial derivatives
    hidden_pd = input_layer_outputs[:, :, np.newaxis] * hidden_error[: , np.newaxis, :]
    output_pd = hidden_layer_outputs[:, :, np.newaxis] * output_error[:, np.newaxis, :]

    # average for total gradients
    total_hidden_gradient = np.average(hidden_pd, axis=0)
    total_output_gradient = np.average(output_pd, axis=0)

    # update weights
    hidden_weights += - rho * total_hidden_gradient
    output_weights += - rho * total_output_gradient

    print("Error: \n{}".format(np.average(hidden_error, axis=0)))

Error: 
[ 0.18957154 -0.26397532  0.06267748]
Error: 
[ 0.18973958 -0.26453585  0.06272476]
Error: 
[ 0.18990758 -0.2650978   0.06277199]
Error: 
[ 0.19007554 -0.26566117  0.06281915]
Error: 
[ 0.19024346 -0.26622596  0.06286625]
Error: 
[ 0.19041134 -0.26679217  0.06291329]
Error: 
[ 0.19057918 -0.26735981  0.06296027]
Error: 
[ 0.19074698 -0.26792888  0.06300719]
Error: 
[ 0.19091473 -0.2684994   0.06305405]
Error: 
[ 0.19108244 -0.26907135  0.06310084]
Error: 
[ 0.19125011 -0.26964476  0.06314757]
Error: 
[ 0.19141773 -0.27021961  0.06319424]
Error: 
[ 0.1915853  -0.27079592  0.06324084]
Error: 
[ 0.19175283 -0.27137369  0.06328738]
Error: 
[ 0.19192032 -0.27195292  0.06333385]
Error: 
[ 0.19208775 -0.27253362  0.06338026]
Error: 
[ 0.19225514 -0.2731158   0.0634266 ]
Error: 
[ 0.19242248 -0.27369945  0.06347288]
Error: 
[ 0.19258976 -0.27428458  0.06351909]
Error: 
[ 0.192757   -0.2748712   0.06356523]
Error: 
[ 0.19292419 -0.27545931  0.06361131]
Error: 
[ 0.19309132 -0.27604891  