In [3]:
import tensorflow

print("HelloWorld")


HelloWorld


# Lab on Machine Learning and Applications in Intelligent Vehicles
## Session 1: Introduction


### Course Plan:

This lab is a continuation to the Machine learning lecture, the objective of this course is to learn how to model and implement neural networks using deep learning python frameworks: 
1. Tensorflow
2. Keras
3. Pytorch

Useing these frameworks, we will go through the following topics and use cases:

#### Session 1: 05.06 - 09:00 - 11:00  :

>#### Presentation:  05.06 - 09:00 - 10:30:
>1. Introduction to deep learning frameworks
2. Deep learning in Numpy

>#### Break:  05.06 - 10:30 - 10:45
>#### Assignment:  05.06 - 10:45 - 11:45 : 
>* Implementation of backprop using numpy

>1. Tensorflow backround 
2. Implementation of feedforward neural networks using Tensorflow

>#### Break:  05.06 - 10:00 - 10:15
>#### Assignment:  05.06 - 10:15 - 10:45 : 
  
  >* play around with tensorflow and build your first neural network



#### Session 2:  05.06 - 11:00 - 12:00  :

>#### Presentation:  05.06 - 11:00 - 12:00:


>3. Implementation of CNN useing Tensorflow
4. Tensorboard

>#### Break:  05.06 - 12:00 - 13:00
>#### Assignment:  05.06 - 13:00 - 13:30 :


 #### Session 3:  05.06 - 13:30 - 15:00  :

>#### Presentation:  05.06 - 13:00 - 14:00:

>5. Introduction to Keras
6. CNN using Keras
>#### Break:  05.06 - 14:00 - 14:15
>#### Assignment:  05.06 - 14:15 - 14:45 :

 #### Session 4:  05.06 - 15:00 - 16:30  :

>#### Presentation:  05.06 - 15:00 - 15:45:

>7. LSTM using Keras

>#### Break:  05.06 - 15:45 - 16:00
>#### Assignment:  05.06 - 16:00 - 16:30 :


8. VGG, Inceptaion, ResNet models using Keras

9. Autoencoders using Keras

10. Sequence to Sequence Models using Keras 

11. Attention Mechanism using Keras
12. GANS 
13. Introduction to Pytorch
14. Machine translation using Pytorch
15. Introduction to Allennlp
16. Deep Reinforcment Learning using Keras
17. Use case: building self driving car using Unity and tensorflow










#Session 1: 05.06 - 09:00 - 11:00 :




## Deep learning frameworks:

In the past decade, many deep learning frameworks have been developed to ease and scale the research and development of AI. Many big technology providers including Google, IBM, Microsoft and Facebook have entered the race to provide the best and most popluar frameworks. To enter such a race, mainly four features are considered in the provided framework:

1. Uses a popular language for data scientists (Python, Scale, C++ or R)
2. Flexible in creating and adjusting deep learning architectures -> Functional programming
3. Easy for computing gradients
4. Interface with GPUs for parallel processing


In the following we see the most popular provided deep learning frameworks with their providers
https://towardsdatascience.com/deep-learning-framework-power-scores-2018-23607ddf297a

![alt text](https://cdn-images-1.medium.com/max/1600/1*dYjDEI0mLpsCOySKUuX1VA.png)

## Tensorflow
TensorFlow is the undisputed heavyweight champion. It has the most GitHub activity, Google searches, Medium articles, books on Amazon and ArXiv articles. It also has the most developers using it and is listed in the most online job descriptions. TensorFlow is backed by Google.

## Keras
Keras has an “API designed for human beings, not machines.” It is the second most popular framework in nearly all evaluation areas. Keras sits on top of TensorFlow, Theano, or CNTK. Start with Keras if you are new to deep learning.

## Pytorch

PyTorch is the third most popular overall framework and the second most popular stand-alone framework. It is younger than TensorFlow and has grown rapidly in popularity. It allows customization that TensorFlow does not. It has the backing of Facebook.

## Theano

Theano was developed at the University of Montreal in 2007 and is the oldest significant Python deep learning framework. It has lost much of its popularity and its leader stated that major releases were no longer on the roadmap. However, updates continue to be made. Theano still the fifth highest scoring framework.

# Comparision:

## Criteria 1: Online Job Listings

TensorFlow is the clear winner when it comes to frameworks mentioned in job listings. Learn it if you want a job doing deep learning.

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*kA8dIgRqLdWgKgs2sd7clA.png)

## Criteria 2: Usage


Keras showed a surprising amount of use — nearly as much as TensorFlow. It’s interesting that US employers are overwhelmingly looking for TensorFlow skills, when — at least internationally — Keras is used almost as frequently.

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*6b2Tm0oFr99zKaxkr4g52w.png)
  
  
## Criteria 4: Google Search Activity

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*wpA6C9x_Nri42EzbqnS1fQ.png)

## Criteria 5: Medium Articles

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*Y1cJUgZTC3u_hU1lmdsroQ.png)


## Criteria 6: Amazon Books

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*mtP47q29T6agdkEoJcCw-w.png)

## Criteria 7 : ArXiv Articles

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*7jdNoNkGlx_1EnfevQXRvw.png)
  
## Criteria 8: GitHub Activity

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*eOOYV3C5klsuVBMX31ngxw.png)
  
 --------------------------------
 


  
 








```
# This is formatted as code
```


Before we jump into Tensorflow, we will implemented our first neural network model using Python Numpy package. NumPy is the fundamental package for scientific computing with Python, such as:

1. Linear Algebra
2. Statistics
3. Calculus

## A brief intro to Numpy operations:

1. Creating a Vector:
Here we use Numpy to create a 1-D Array which we then call a vector.





In [0]:
import numpy as np

v1=np.zeros((1,100))
#display(v1)


v2=np.zeros((1,100))
#display(v2)

v2.T.shape

v3=np.ones((1,100))
v4=np.eye(4)
v5=np.random.randn(100,1) # normally distributed random generator with mean 0 and 1 std
v6=np.random.rand(100,1) # uniformally distributed random generator between 0 and 1
display(v4)
display('mean of randn: ',v5.mean())
display('std of randn: ',v5.std())
display('mean of rand: ',v6.mean())
display('min of rand: ',v6.min())
display('max of rand: ',v6.max())

2. Creating a Matrix
We Create a 2-D Array in Numpy and call it a Matrix. It contains 2 rows and 3 columns.

In [29]:
m1=np.zeros((2,3))
display(m1)

matrix=np.array([[1,2,3],[4,5,6]])
display('matrix: ',matrix)
display('matrix shape: ',matrix.shape)

array([[0., 0., 0.],
       [0., 0., 0.]])

'matrix: '

array([[1, 2, 3],
       [4, 5, 6]])

'matrix shape: '

(2, 3)

3. Selecting Elements


In [39]:
display(matrix[0,0]) # first row first column
display(matrix[0,-1]) # first row last column
display(matrix[0,-2]) # first row second last column
display(matrix[0,1:]) # first row and all columns after the first
display(matrix[0,:-1]) # first row and all columns until the last

# Always consider that the left side of : will be included, but the right side not
display(matrix[0,0:2]) # e.g. this will only give the first and second column

1

3

2

array([2, 3])

array([1, 2])

array([1, 2])

4. Describing a Matrix

In [41]:
#View the number of rows and columns
print(matrix.shape)
#View the number of elements (rows*columns)
print(matrix.size)
#View the number of dimensions (2 in this case)
print(matrix.ndim)

(2, 3)
6
2


5. Finding the max and min values

In [62]:
print(matrix)
print(matrix.max())
print(matrix[0,:].max())
print(matrix.min(axis=0)) #Minimum along the first dimension

print(np.min(matrix,axis=0)) #Minimum along the first dimension
print('arg:',np.argmax(matrix,axis=0)) #Argument (index) of the minimum along the first dimension
print('arg:',np.argmax(matrix)) #Argument (index) of the minimum in the matrix

print('MaxIndex:',np.argwhere(matrix == matrix.max()))
print('Indices with values smaller than max:',np.argwhere(matrix < matrix.max()))


testmatrix=np.array([[6,2,3],[4,5,6]])
print(testmatrix.argmax(axis=0))

[[1 2 3]
 [4 5 6]]
6
3
[1 2 3]
[1 2 3]
arg: [1 1 1]
arg: 5
MaxIndex: [[1 2]]
Indices with values smaller than max: [[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]]
[0 1 1]


6. Reshaping Arrays


In [68]:
matrix.shape
matrix2=matrix.reshape((3,2))
matrix.reshape((1,6))
matrix.reshape((1,2,3)) #dim 0 size is 1, dim 1 is 2, dim 2 is 3
matrix.reshape((1,-1,3)).shape #Calculate the size of one dimension automatically

(1, 2, 3)

7. Calculating Dot Products

In [70]:
vector_1=np.array([1,2,3])
vector_2=np.array([4,5,6])

#Calculate the dot product
print(np.dot(vector_1,vector_2))
#Alternatively you can use @ to calculate dot products
print(vector_1@vector_2)


matrix2.dot(matrix)

32
32


array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

##Linear regression in Numpy:

---



Write the numpy code for the following model:

$Y=WX+B$

where $X$ is 3x10 matrix:  10 samples and 3 features

$Y$ is 4x10 matrix: 10 samples and 4 outputs

$W$ is the weights matrix with the shape 4x3: connecting 3 inputs to 4 outputs

$b$ is a vector with a size 4 ( one bias per output)


In [76]:
#Inputs or features matrix
X=np.random.rand(3,10)
display('shape of X:',X.shape)

#Weights matrix
W=np.random.rand(4,3)

#bias
b=np.zeros((4,)) # This is a vector
b=np.zeros((4,1)) # This is a matrix

#regression model
Y=np.dot(W,X)+b  # 4x3 , 3x10

display('Y: ',Y.shape)


'shape of X:'

(3, 10)

'Y: '

(4, 10)

## One neuron model in numpy:

A single neuron has multiple inputs and one output, in addition to the linear regression model, we need to add non linearity through an activation function:

$Y= f(WX+B)$

where $X$ is n x m matrix:  m samples and n features/inputs

$f(g)= \frac{1}{1+\exp(-g)}$  is a sigmoid acitavation function

$Y$ is nh1 x m matrix: m samples and ny outputs

$W$ is the weights matrix with the shape nh1 x n: connecting 3 inputs to 4 outputs

$b$ is a vector with a size nh1 ( one bias per output)





In [0]:
#Function definition with def
def f(x):
  return 1.0/(1.0 + np.exp(-x))


num_inputs=3
num_outputs=1
num_samples=100

#Function definition with lambda
f=lambda x: 1.0/(1.0 + np.exp(-x)) # activation function (use sigmoid function)

#Inputs or features matrix
X=np.random.rand(num_inputs,num_samples)

#Weights matrix
W=np.random.rand(num_outputs,num_inputs)

#bias
b=np.random.rand(num_outputs,1)

#regression model
Y=f(np.dot(W,X)+b)
display(Y)
display(Y.shape)

## One hidden layer model in numpy:

The difference from the one neuron model is simple:  we need only to change the number of output "ny"

In [0]:


num_inputs=3
num_outputs=3
hidden_layer_1_outputs=4
hidden_layer_2_outputs=3
num_samples=100

#Function definition with lambda
f=lambda x: 1.0/(1.0 + np.exp(-x)) # activation function (use sigmoid function)

#Inputs or features matrix
X=np.random.rand(num_inputs,num_samples)

#Weights matrix of the first hidden layer
W_h1=np.random.rand(hidden_layer_1_outputs,num_inputs)
#Weights matrix of second hidden layer
W_h2=np.random.rand(hidden_layer_2_outputs,hidden_layer_1_outputs)

#bias
b_h1=np.random.rand(hidden_layer_1_outputs,1)
b_h2=np.random.rand(hidden_layer_2_outputs,1)

# Calculate output of hidden layer 1
h1=f(np.dot(W_h1,X)+b_h1)
display(h1.shape)
# Calculate output of hidden layer 2
h2=f(np.dot(W_h2,h1)+b_h2)

display(h2)
display(h2.shape)

## Gradient descent in Numpy:
Let us now start training a neural network
We start by implementing a simple gradient descent for linear regression

In [93]:
converged = False
iter=0
m=10 #Number of samples
ni=1 #Number of input neurons
h=1 #Number of hidden layers
no=1 #Number of neurons in the output layer

#Generate a random X
X=np.random.rand(m)

#learning rate
alpha=0.1

#early stop criteria
ep=0.001

#maximum number of training iterations
max_iter=100

#Generate random weights vector for the output layer
W1=np.random.rand()

#Generator a random bias for the output layer
b1=np.random.rand()

#Generate a random ground truth
Y_gr=np.random.rand(m)

J=sum([(b1 + W1*X[i] - Y_gr[i])**2 for i in range(m)]) #cost function

while not converged:
  #for each training sample, compute the gradient (d/d_theta j(theta))
  grad0=1.0/m*sum([(b1 + W1*X[i] - Y_gr[i]) for i in range(m)])
  grad1=1.0/m*sum([(b1 + W1*X[i] - Y_gr[i])*X[i] for i in range(m)])
  
  #update the theta_temp
  temp0 = b1 - alpha * grad0
  temp1 = W1 - alpha * grad1
  
  #update theta
  b1=temp0
  W1=temp1
  
  #sum squared error
  e = sum([(b1 + W1*X[i] - Y_gr[i])**2 for i in range(m)])
  
  print('Iteration: ',iter, 'current error: ',e)
  
  if abs(J-e) <= ep:
    print('Converged, iterations: ',iter, '!!')
    converged = True
  
  J=e
  iter += 1
  
  if iter == max_iter:
    print('Maximum iterations reached!')
    converged=True



Iteration:  0 current error:  1.258772941147398
Iteration:  1 current error:  1.0584213915446599
Iteration:  2 current error:  0.910979760011104
Iteration:  3 current error:  0.8024641609280126
Iteration:  4 current error:  0.7225866483626499
Iteration:  5 current error:  0.663778379295766
Iteration:  6 current error:  0.6204709547864042
Iteration:  7 current error:  0.5885677026509099
Iteration:  8 current error:  0.5650547001181425
Iteration:  9 current error:  0.5477146031882774
Iteration:  10 current error:  0.5349161108857141
Iteration:  11 current error:  0.5254590741052568
Iteration:  12 current error:  0.5184605421867958
Iteration:  13 current error:  0.5132709273777554
Iteration:  14 current error:  0.5094123270262385
Iteration:  15 current error:  0.5065331472171357
Iteration:  16 current error:  0.5043747193801844
Iteration:  17 current error:  0.502746740127757
Iteration:  18 current error:  0.5015092023429579
Iteration:  19 current error:  0.5005591018807148
Converged, ite

# Test 1

##Assignment 1
### Backpropagation in Numpy:


In [171]:
iter = 0
max_iter = 100

num_inputs=3
num_outputs=3
hidden_layer_1_outputs=4
hidden_layer_2_outputs=3
num_samples=50

#Function definition with lambda
f=lambda x: 1.0/(1.0 + np.exp(-x)) # activation function (use sigmoid function)
fd=lambda x: x * (1 - x) # activation function (use sigmoid function)

#Inputs or features matrix
X=np.random.rand(num_samples,num_inputs)
X = np.hstack((np.ones((X.shape[0], 1)), X))

#Weights matrix of the first hidden layer
W_h1=np.random.rand(num_inputs+1,hidden_layer_1_outputs)
#Weights matrix of second hidden layer
W_h2=np.random.rand(hidden_layer_1_outputs+1,hidden_layer_2_outputs)


#Ground truth
Y=np.random.rand(num_samples,hidden_layer_2_outputs)

converged = False

while not converged:
  ###### Forward propagation
  # Calculate output of hidden layer 1
  h1=f(np.dot(X,W_h1))
  
  #Append a column with ones representing the bias
  h1 = np.hstack((np.ones((X.shape[0], 1)), X))
  display(h1.shape)
  # Calculate output of hidden layer 2 - no activation function
  h2=np.dot(h1,W_h2)
  
  ###### Starting the backpropagation
  #error
  J=h2 - Y
  err=np.sum(np.square(h2 - Y))

  
  #Gradient of the output layer
  grad_h2 = h2*J
  
  #error of the hidden layer
  hidden_error = h1[:, 1:] * (1 - h1[:, 1:]) * np.dot(grad_h2, W_h2.T[:, 1:])
  
  #Gradient of the hidden layer
  grad_h1 = h1[:,:,np.newaxis]*hidden_error[:,np.newaxis,:]
  
  #Average gradient
  total_output_gradient=np.average(grad_h2,axis=0)
  total_hidden_gradient=np.average(grad_h1,axis=0)
  
  #Update the weights
  W_h2+= - alpha*total_output_gradient;
  W_h1+= - alpha*total_hidden_gradient[1:,:];
  
  print('Iteration: ',iter,'Error: ',err);
  iter +=1
  
  if iter >= max_iter:
    converged = True
  
  




(50, 5)

Iteration:  0 Error:  307.01926783148457


(50, 5)

Iteration:  1 Error:  36.31262674167145


(50, 5)

Iteration:  2 Error:  25.20905957538629


(50, 5)

Iteration:  3 Error:  20.74508296832306


(50, 5)

Iteration:  4 Error:  18.62046935649575


(50, 5)

Iteration:  5 Error:  17.528794839443513


(50, 5)

Iteration:  6 Error:  16.9501517906131


(50, 5)

Iteration:  7 Error:  16.645033347914676


(50, 5)

Iteration:  8 Error:  16.49227922218816


(50, 5)

Iteration:  9 Error:  16.426516284028466


(50, 5)

Iteration:  10 Error:  16.41081862552815


(50, 5)

Iteration:  11 Error:  16.423640515705788


(50, 5)

Iteration:  12 Error:  16.45213203886333


(50, 5)

Iteration:  13 Error:  16.488532724982896


(50, 5)

Iteration:  14 Error:  16.528141086758275


(50, 5)

Iteration:  15 Error:  16.568131232771094


(50, 5)

Iteration:  16 Error:  16.606843484018334


(50, 5)

Iteration:  17 Error:  16.64334930542926


(50, 5)

Iteration:  18 Error:  16.677179551327


(50, 5)

Iteration:  19 Error:  16.708152294982035


(50, 5)

Iteration:  20 Error:  16.736262618782803


(50, 5)

Iteration:  21 Error:  16.761611611457


(50, 5)

Iteration:  22 Error:  16.784360520831804


(50, 5)

Iteration:  23 Error:  16.80470122599501


(50, 5)

Iteration:  24 Error:  16.822837384946745


(50, 5)

Iteration:  25 Error:  16.838972604465102


(50, 5)

Iteration:  26 Error:  16.85330324084923


(50, 5)

Iteration:  27 Error:  16.866014251882106


(50, 5)

Iteration:  28 Error:  16.877277049099405


(50, 5)

Iteration:  29 Error:  16.887248647696886


(50, 5)

Iteration:  30 Error:  16.89607164294076


(50, 5)

Iteration:  31 Error:  16.903874697088767


(50, 5)

Iteration:  32 Error:  16.910773325441113


(50, 5)

Iteration:  33 Error:  16.91687084100872


(50, 5)

Iteration:  34 Error:  16.92225936543798


(50, 5)

Iteration:  35 Error:  16.927020846585027


(50, 5)

Iteration:  36 Error:  16.931228045388977


(50, 5)

Iteration:  37 Error:  16.934945469762532


(50, 5)

Iteration:  38 Error:  16.93823024335115


(50, 5)

Iteration:  39 Error:  16.94113290374854


(50, 5)

Iteration:  40 Error:  16.943698129156452


(50, 5)

Iteration:  41 Error:  16.94596539527314


(50, 5)

Iteration:  42 Error:  16.947969565892947


(50, 5)

Iteration:  43 Error:  16.94974142165378


(50, 5)

Iteration:  44 Error:  16.951308131822206


(50, 5)

Iteration:  45 Error:  16.95269367412849


(50, 5)

Iteration:  46 Error:  16.95391920757405


(50, 5)

Iteration:  47 Error:  16.955003402911608


(50, 5)

Iteration:  48 Error:  16.955962735200714


(50, 5)

Iteration:  49 Error:  16.95681174250472


(50, 5)

Iteration:  50 Error:  16.957563254445947


(50, 5)

Iteration:  51 Error:  16.95822859398942


(50, 5)

Iteration:  52 Error:  16.958817755492596


(50, 5)

Iteration:  53 Error:  16.959339561745466


(50, 5)

Iteration:  54 Error:  16.959801802435152


(50, 5)

Iteration:  55 Error:  16.960211356202905


(50, 5)

Iteration:  56 Error:  16.960574298219953


(50, 5)

Iteration:  57 Error:  16.960895994990178


(50, 5)

Iteration:  58 Error:  16.961181187891782


(50, 5)

Iteration:  59 Error:  16.96143406679476


(50, 5)

Iteration:  60 Error:  16.961658334934874


(50, 5)

Iteration:  61 Error:  16.9618572660859


(50, 5)

Iteration:  62 Error:  16.962033754948706


(50, 5)

Iteration:  63 Error:  16.96219036156686


(50, 5)

Iteration:  64 Error:  16.962329350481763


(50, 5)

Iteration:  65 Error:  16.962452725255392


(50, 5)

Iteration:  66 Error:  16.96256225891348


(50, 5)

Iteration:  67 Error:  16.962659520795768


(50, 5)

Iteration:  68 Error:  16.962745900241693


(50, 5)

Iteration:  69 Error:  16.96282262748834


(50, 5)

Iteration:  70 Error:  16.962890792112436


(50, 5)

Iteration:  71 Error:  16.962951359308267


(50, 5)

Iteration:  72 Error:  16.963005184258442


(50, 5)

Iteration:  73 Error:  16.963053024823555


(50, 5)

Iteration:  74 Error:  16.963095552749902


(50, 5)

Iteration:  75 Error:  16.963133363570325


(50, 5)

Iteration:  76 Error:  16.963166985352572


(50, 5)

Iteration:  77 Error:  16.963196886430914


(50, 5)

Iteration:  78 Error:  16.963223482240785


(50, 5)

Iteration:  79 Error:  16.963247141361748


(50, 5)

Iteration:  80 Error:  16.963268190861655


(50, 5)

Iteration:  81 Error:  16.963286921023933


(50, 5)

Iteration:  82 Error:  16.963303589529946


(50, 5)

Iteration:  83 Error:  16.963318425160256


(50, 5)

Iteration:  84 Error:  16.963331631070574


(50, 5)

Iteration:  85 Error:  16.963343387692156


(50, 5)

Iteration:  86 Error:  16.963353855300014


(50, 5)

Iteration:  87 Error:  16.963363176287558


(50, 5)

Iteration:  88 Error:  16.963371477181713


(50, 5)

Iteration:  89 Error:  16.96337887042832


(50, 5)

Iteration:  90 Error:  16.96338545597444


(50, 5)

Iteration:  91 Error:  16.963391322670955


(50, 5)

Iteration:  92 Error:  16.963396549516034


(50, 5)

Iteration:  93 Error:  16.96340120675779


(50, 5)

Iteration:  94 Error:  16.963405356872272


(50, 5)

Iteration:  95 Error:  16.963409055430994


(50, 5)

Iteration:  96 Error:  16.96341235187066


(50, 5)

Iteration:  97 Error:  16.963415290176243


(50, 5)

Iteration:  98 Error:  16.963417909487248


(50, 5)

Iteration:  99 Error:  16.963420244635884
