# Lab on Machine Learning and Applications in Intelligent Vehicles
## Session 1: Introduction


### Course Plan:

This lab is a continuation to the Machine learning lecture, the objective of this course is to learn how to model and implement neural networks using deep learning python frameworks: 
1. Tensorflow
2. Keras
3. Pytorch

Useing these frameworks, we will go through the following topics and use cases:

#### Session 1: 05.06 - 09:00 - 11:00  :

>#### Presentation:  05.06 - 09:00 - 10:30:
>1. Introduction to deep learning frameworks
2. Deep learning in Numpy

>#### Break:  05.06 - 10:30 - 10:45
>#### Assignment:  05.06 - 10:45 - 11:45 : 
>* Implementation of backprop using numpy

>1. Tensorflow backround 
2. Implementation of feedforward neural networks using Tensorflow

>#### Break:  05.06 - 10:00 - 10:15
>#### Assignment:  05.06 - 10:15 - 10:45 : 
  
  >* play around with tensorflow and build your first neural network



#### Session 2:  05.06 - 11:00 - 12:00  :

>#### Presentation:  05.06 - 11:00 - 12:00:


>3. Implementation of CNN useing Tensorflow
4. Tensorboard

>#### Break:  05.06 - 12:00 - 13:00
>#### Assignment:  05.06 - 13:00 - 13:30 :


 #### Session 3:  05.06 - 13:30 - 15:00  :

>#### Presentation:  05.06 - 13:00 - 14:00:

>5. Introduction to Keras
6. CNN using Keras
>#### Break:  05.06 - 14:00 - 14:15
>#### Assignment:  05.06 - 14:15 - 14:45 :

 #### Session 4:  05.06 - 15:00 - 16:30  :

>#### Presentation:  05.06 - 15:00 - 15:45:

>7. LSTM using Keras

>#### Break:  05.06 - 15:45 - 16:00
>#### Assignment:  05.06 - 16:00 - 16:30 :


8. VGG, Inceptaion, ResNet models using Keras

9. Autoencoders using Keras

10. Sequence to Sequence Models using Keras 

11. Attention Mechanism using Keras
12. GANS 
13. Introduction to Pytorch
14. Machine translation using Pytorch
15. Introduction to Allennlp
16. Deep Reinforcment Learning using Keras
17. Use case: building self driving car using Unity and tensorflow










#Session 1: 05.06 - 09:00 - 11:00 :




## Deep learning frameworks:

In the past decade, many deep learning frameworks have been developed to ease and scale the research and development of AI. Many big technology providers including Google, IBM, Microsoft and Facebook have entered the race to provide the best and most popluar frameworks. To enter such a race, mainly four features are considered in the provided framework:

1. Uses a popular language for data scientists (Python, Scale, C++ or R)
2. Flexible in creating and adjusting deep learning architectures -> Functional programming
3. Easy for computing gradients
4. Interface with GPUs for parallel processing


In the following we see the most popular provided deep learning frameworks with their providers
https://towardsdatascience.com/deep-learning-framework-power-scores-2018-23607ddf297a

![alt text](https://cdn-images-1.medium.com/max/1600/1*dYjDEI0mLpsCOySKUuX1VA.png)

## Tensorflow
TensorFlow is the undisputed heavyweight champion. It has the most GitHub activity, Google searches, Medium articles, books on Amazon and ArXiv articles. It also has the most developers using it and is listed in the most online job descriptions. TensorFlow is backed by Google.

## Keras
Keras has an “API designed for human beings, not machines.” It is the second most popular framework in nearly all evaluation areas. Keras sits on top of TensorFlow, Theano, or CNTK. Start with Keras if you are new to deep learning.

## Pytorch

PyTorch is the third most popular overall framework and the second most popular stand-alone framework. It is younger than TensorFlow and has grown rapidly in popularity. It allows customization that TensorFlow does not. It has the backing of Facebook.

## Theano

Theano was developed at the University of Montreal in 2007 and is the oldest significant Python deep learning framework. It has lost much of its popularity and its leader stated that major releases were no longer on the roadmap. However, updates continue to be made. Theano still the fifth highest scoring framework.

# Comparision:

## Criteria 1: Online Job Listings

TensorFlow is the clear winner when it comes to frameworks mentioned in job listings. Learn it if you want a job doing deep learning.

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*kA8dIgRqLdWgKgs2sd7clA.png)

## Criteria 2: Usage


Keras showed a surprising amount of use — nearly as much as TensorFlow. It’s interesting that US employers are overwhelmingly looking for TensorFlow skills, when — at least internationally — Keras is used almost as frequently.

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*6b2Tm0oFr99zKaxkr4g52w.png)
  
  
## Criteria 4: Google Search Activity

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*wpA6C9x_Nri42EzbqnS1fQ.png)

## Criteria 5: Medium Articles

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*Y1cJUgZTC3u_hU1lmdsroQ.png)


## Criteria 6: Amazon Books

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*mtP47q29T6agdkEoJcCw-w.png)

## Criteria 7 : ArXiv Articles

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*7jdNoNkGlx_1EnfevQXRvw.png)
  
## Criteria 8: GitHub Activity

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*eOOYV3C5klsuVBMX31ngxw.png)
  
 --------------------------------
 


  
 








```
# This is formatted as code
```


Before we jump into Tensorflow, we will implemented our first neural network model using Python Numpy package. NumPy is the fundamental package for scientific computing with Python, such as:

1. Linear Algebra
2. Statistics
3. Calculus

## A brief intro to Numpy operations:

1. Creating a Vector:
Here we use Numpy to create a 1-D Array which we then call a vector.





In [59]:
import numpy as np

v1=np.zeros((1,100))
#display(v1)
#display(v1.shape)   
#display(v1.T.shape) #transpose

v1=np.ones((1,100))
#display(v1)

v1=np.random.randn(100,1) #normal distributed random variable 0 mean, 1 standard deviation
v1=np.random.rand(100,1)
#display(v1)

display('mean:',v1.mean())
display('std: ',v1.std())
display('max: ',v1.max())
display('min: ',v1.min())


     

'mean:'

0.5162576846562591

'std: '

0.29658603209996637

'max: '

0.9949323699475169

'min: '

0.0014838949064867046

2. Creating a Matrix
We Create a 2-D Array in Numpy and call it a Matrix. It contains 2 rows and 3 columns.

In [22]:
m1=np.zeros((2,3))
m1=np.array([[1,2,3],[4,5,6]])
display(m1)

array([[1, 2, 3],
       [4, 5, 6]])

3. Selecting Elements


In [32]:
display(m1[0]) #first row

display(m1[1,1]) #element at 1,1

display(m1[0,-1]) #last element of the first row

display(m1[0,-2]) #second last element of the first row

display(m1[0,1:]) #last two elements of the first row

display(m1[0,:-1]) #first tow elements of the first row


array([1, 2, 3])

5

3

2

array([2, 3])

array([1, 2])

4. Describing a Matrix

In [33]:
display(m1.shape)
display(m1.size) #number of elements
display(m1.ndim) #dimensions

(2, 3)

6

2

5. Finding the max and min values

In [44]:
#same as for vectors
m1.min(axis=0) #smallest of each row

#or

np.min(m1,axis=0)
np.max(m1,axis=0)

#to get the index of the row
np.argmax(m1,axis=0)

#to get the index of the max value
np.argmax(m1)

#search for condition
np.argwhere(m1<np.mean(m1))

array([[0, 0],
       [0, 1],
       [0, 2]])

6. Reshaping Arrays


In [54]:
m2=np.array([[1,2,3],[4,5,6]])
m2.shape
m2.reshape((3,2)) #same as transpose
m2.reshape((6,1)) #flatten (column)
m2.reshape((1,6)) #also flatten but row vector
m2.reshape((1,2,3)) #dim 0 size 1 dim 1 size 2 dim 2 size 3
m2.reshape((1,-1,3)) #hmmm

array([[[1, 2, 3],
        [4, 5, 6]]])

7. Calculating Dot Products

In [57]:
v1=np.array([1,2,3])
v2=np.array([4,5,6])

display(np.dot(v1,v2)) #dot product
display(v1 @ v2) #also dot product but shorter

32

32

##Linear regression in Numpy:

---



Write the numpy code for the following model:

$Y=WX+B$

where $X$ is 3x10 matrix:  10 samples and 3 features

$Y$ is 4x10 matrix: 10 samples and 4 outputs

$W$ is the weights matrix with the shape 4x3: connecting 3 inputs to 4 outputs

$b$ is a vector with a size 4 ( one bias per output)


In [62]:
#input for feature matrix
X=np.random.rand(3,10)

#weight matrix
W=np.random.rand(4,3)

#bias vector
b=np.zeros((4,1))   # not the same as np.zeros(4,) is a vector than

#regression model
Y=np.dot(W,X)+b
display('Y shape: ',Y.shape)

'Y shape: '

(4, 10)

## One neuron model in numpy:

A single neuron has multiple inputs and one output, in addition to the linear regression model, we need to add non linearity through an activation function:

$Y= f(WX+B)$

where $X$ is n x m matrix:  m samples and n features/inputs

$f(g)= \frac{1}{1+\exp(-g)}$  is a sigmoid acitavation function

$Y$ is nh1 x m matrix: m samples and ny outputs

$W$ is the weights matrix with the shape nh1 x n: connecting 3 inputs to 4 outputs

$b$ is a vector with a size nh1 ( one bias per output)





In [0]:
#each neuron has one output but three inputs therefore we need four neurons

num_inputs=3
num_outputs=4
num_samples=100

f= lambda x: 1.0/(1.0+np.exp(-x)) # activation function

#or we can write like that
#def f(x):
#  return 1.0/(1.0+np.exp(-x))

#input for feature matrix
X=np.random.rand(num_inputs,num_samples)

#weight matrix
W=np.random.rand(num_outputs,num_inputs)

#bias vector
b=np.random.rand(num_outputs,1)   # not the same as np.zeros(4,) is a vector than

#regression model
Y=f(np.dot(W,X)+b)   #only difference to before
display('Y shape: ',Y.shape)
display('Y: ',Y)

## Two hidden layer model in numpy:

The difference from the one neuron model is simple:  we need only to change the number of output "ny"

In [77]:
#each neuron has one output but three inputs therefore we need four neurons

num_inputs=3
num_hidden_outputs=4
num_outputs=3
num_samples=100

f= lambda x: 1.0/(1.0+np.exp(-x)) # activation function

#or we can write like that
#def f(x):
#  return 1.0/(1.0+np.exp(-x))

#input for feature matrix
X=np.random.rand(num_inputs,num_samples)

#weight matrix
W1=np.random.rand(num_hidden_outputs,num_inputs)
W2=np.random.rand(num_outputs,num_hidden)

#bias vector
b1=np.random.rand(num_hidden_outputs,1)   # not the same as np.zeros(4,) is a vector than
b2=np.random.rand(num_outputs,1)

#hidden layer 1 output
Y1=f(np.dot(W1,X)+b1)   #only difference to before
display('Y1 shape: ',Y1.shape)
#display('Y1: ',Y1)

#output (layer 2)
Y=f(np.dot(W2,Y1)+b2)
display('Y shape: ',Y.shape)
#display('Y: ',Y)


'Y1 shape: '

(4, 100)

'Y shape: '

(3, 100)

## Gradient descent in Numpy:
Let us now start training a neural network
We start by implementing a simple gradient descent for linear regression

In [88]:
m = 10 #number of samples
ni=1   #num of input layers
h=1    #num of hidden layers
no=1   #num of output layers

#Input vector
X=np.random.rand(m)

#Learning rate
alpha=0.01

#Early stop criteria
ep=0.001

#Maximum iteration
max_iter=1000

#Generate a random wight for output
W1=np.random.rand()

#Generate the bias
b1=np.random.rand()

#Generate a random ground truth
Y_gr=np.random.rand(m)

J=sum([(b1+W1*X[i]-Y_gr[i])**2 for i in range(m)]) #Cost function sum of 

converged=False
iter=0

while not converged:
  grad0=1.0/m*sum([(b1+W1*X[i]-Y_gr[i]) for i in range(m)])
  grad1=1.0/m*sum([(b1+W1*X[i]-Y_gr[i])*X[i] for i in range(m)])
  
  #update the theta_temp
  temp0=b1-alpha*grad0
  temp1=W1-alpha*grad1
  
  #update theta
  b1=temp0
  W1=temp1
  
  #sum squared error
  e=sum([(b1+W1*X[i]-Y_gr[i])**2 for i in range(m)])
  
  if abs(J-e)<=ep:
    print('Converged, iterations: ',iter,'!!!')
    converged=True;
    
  J=e #update error
  print('Error at iteration ',iter,' is ',J)
  iter +=1
  
  if iter==max_iter:
    print('Maximum iterations reached!')
    converged=True

Error at iteration  0  is  3.551982878625796
Error at iteration  1  is  3.4753354358128856
Error at iteration  2  is  3.400659250043203
Error at iteration  3  is  3.3279035876289145
Error at iteration  4  is  3.257019020632688
Error at iteration  5  is  3.1879573932611094
Error at iteration  6  is  3.120671789123052
Error at iteration  7  is  3.0551164993307154
Error at iteration  8  is  2.9912469914216744
Error at iteration  9  is  2.9290198790807827
Error at iteration  10  is  2.868392892641361
Error at iteration  11  is  2.809324850345604
Error at iteration  12  is  2.7517756303446683
Error at iteration  13  is  2.6957061434194065
Error at iteration  14  is  2.6410783064031955
Error at iteration  15  is  2.5878550162887954
Error at iteration  16  is  2.536000125001623
Error at iteration  17  is  2.4854784148223024
Error at iteration  18  is  2.4362555744417698
Error at iteration  19  is  2.3882981756326562
Error at iteration  20  is  2.3415736505210902
Error at iteration  21  is  2.

##Assignment 1
### Backpropagation in Numpy:


In [122]:
num_inputs = 4
hidden_layer_1_outputs = 4
hidden_layer_2_outputs = 3

num_samples = 10

f = lambda x: 1.0/(1.0 + np.exp(-x)) # activation function (use sigmoid)


X = np.random.rand(num_samples,num_inputs-1) # 10x4

X = np.hstack((np.ones((X.shape[0], 1)), X))

display(X.shape)

# Generate a random weights vector for the first hidden layer
W_h1 = np.random.rand(num_inputs,hidden_layer_1_outputs) # 4x4

# Generate a random weights vector for the second hidden layer
W_h2 = np.random.rand(hidden_layer_1_outputs+1,hidden_layer_2_outputs)




# Calculate output of hidden layer 1
h1= f(np.dot(X,W_h1))
display(h1.shape)

# Calculate output of hidden layer 2
#h2= f(np.dot(h1,W_h2))
#display(h2.shape)


# learning rate
alpha =0.01

# early stop criteria 
ep=0.001


# maximum number of training iterations
max_iter=100

# Generate a random ground truth
Y_gr = np.random.rand(hidden_layer_2_outputs,num_samples)

#J = sum([(h2 - Y_gr[:,i])**2 for i in range(num_samples)]) #cost function sum of squared error
print(J)

#while not converged:
for i in range(100):
        #print('Interations:' , iter)
    
        # forward prop   
        # Calculate output of hidden layer 1
        h1= f(np.dot(X,W_h1))
        
        # append a column with ones representing bias inputs
        h1 = np.hstack((np.ones((h1.shape[0], 1)), h1))
        # Calculate output of hidden layer 2
        h2= f(np.dot(h1,W_h2))
        
        
        #error/error 
               
        J = np.sum(np.square(h2- Y_gr.T))
        
        # gradient of the output layer
        grad_h2 = h2*J
        
       
      
        
        # error
        
        #display('h1', (h1[:, 1:] * (1 - h1[:, 1:])).shape)
        
        
        #display('dot ', np.dot(grad_h2, W_h2.T[:, 1:]).shape)


        hidden_error = (h1[:, 1:] * (1 - h1[:, 1:])) * np.dot(grad_h2, W_h2.T[:, 1:]) 

        #print(h1.shape)
        #print(hidden_error.shape)
        grad_h1= h1[:, :, np.newaxis]*hidden_error[:, np.newaxis, :]

      
        # average gradient
        total_hidden_gradient_h2 = np.average(grad_h2, axis=0)
        total_output_gradient_h1 = np.average(grad_h1, axis=0)
        #print(grad_h1.shape)
        #print(W_h1.shape)

        # update weights
        W_h2 += - alpha * total_hidden_gradient_h2
        W_h1 += - alpha * total_output_gradient_h1[1:,:]
        
        
        print('iter',i)
        
        print('cost',J)

(10, 4)

(10, 4)

230.63267595403136
iter 0
cost 6.967904327155814
iter 1
cost 6.253331561872703
iter 2
cost 5.634467242421168
iter 3
cost 5.108369592183296
iter 4
cost 4.666187962033291
iter 5
cost 4.296961012768637
iter 6
cost 3.98974555617948
iter 7
cost 3.734629803544964
iter 8
cost 3.5230915390583424
iter 9
cost 3.3480152269611914
iter 10
cost 3.2035564230386653
iter 11
cost 3.0849553444945914
iter 12
cost 2.9883491932902007
iter 13
cost 2.9106041049909894
iter 14
cost 2.8491730517914897
iter 15
cost 2.8019793217617157
iter 16
cost 2.767322537758351
iter 17
cost 2.743803475799404
iter 18
cost 2.730264101779923
iter 19
cost 2.725739725904436
iter 20
cost 2.7294207237281856
iter 21
cost 2.740621784240535
iter 22
cost 2.758757082003074
iter 23
cost 2.7833201266652754
iter 24
cost 2.8138673267548486
iter 25
cost 2.8500045269785708
iter 26
cost 2.891375950940296
iter 27
cost 2.9376551143270233
iter 28
cost 2.988537375565789
iter 29
cost 3.043733868339421
iter 30
cost 3.1029666183567115
iter 31
cost 3.16