In [3]:
import tensorflow

print("HelloWorld")


HelloWorld


# Lab on Machine Learning and Applications in Intelligent Vehicles
## Session 1: Introduction


### Course Plan:

This lab is a continuation to the Machine learning lecture, the objective of this course is to learn how to model and implement neural networks using deep learning python frameworks: 
1. Tensorflow
2. Keras
3. Pytorch

Useing these frameworks, we will go through the following topics and use cases:

#### Session 1: 05.06 - 09:00 - 11:00  :

>#### Presentation:  05.06 - 09:00 - 10:30:
>1. Introduction to deep learning frameworks
2. Deep learning in Numpy

>#### Break:  05.06 - 10:30 - 10:45
>#### Assignment:  05.06 - 10:45 - 11:45 : 
>* Implementation of backprop using numpy

>1. Tensorflow backround 
2. Implementation of feedforward neural networks using Tensorflow

>#### Break:  05.06 - 10:00 - 10:15
>#### Assignment:  05.06 - 10:15 - 10:45 : 
  
  >* play around with tensorflow and build your first neural network



#### Session 2:  05.06 - 11:00 - 12:00  :

>#### Presentation:  05.06 - 11:00 - 12:00:


>3. Implementation of CNN useing Tensorflow
4. Tensorboard

>#### Break:  05.06 - 12:00 - 13:00
>#### Assignment:  05.06 - 13:00 - 13:30 :


 #### Session 3:  05.06 - 13:30 - 15:00  :

>#### Presentation:  05.06 - 13:00 - 14:00:

>5. Introduction to Keras
6. CNN using Keras
>#### Break:  05.06 - 14:00 - 14:15
>#### Assignment:  05.06 - 14:15 - 14:45 :

 #### Session 4:  05.06 - 15:00 - 16:30  :

>#### Presentation:  05.06 - 15:00 - 15:45:

>7. LSTM using Keras

>#### Break:  05.06 - 15:45 - 16:00
>#### Assignment:  05.06 - 16:00 - 16:30 :


8. VGG, Inceptaion, ResNet models using Keras

9. Autoencoders using Keras

10. Sequence to Sequence Models using Keras 

11. Attention Mechanism using Keras
12. GANS 
13. Introduction to Pytorch
14. Machine translation using Pytorch
15. Introduction to Allennlp
16. Deep Reinforcment Learning using Keras
17. Use case: building self driving car using Unity and tensorflow










#Session 1: 05.06 - 09:00 - 11:00 :




## Deep learning frameworks:

In the past decade, many deep learning frameworks have been developed to ease and scale the research and development of AI. Many big technology providers including Google, IBM, Microsoft and Facebook have entered the race to provide the best and most popluar frameworks. To enter such a race, mainly four features are considered in the provided framework:

1. Uses a popular language for data scientists (Python, Scale, C++ or R)
2. Flexible in creating and adjusting deep learning architectures -> Functional programming
3. Easy for computing gradients
4. Interface with GPUs for parallel processing


In the following we see the most popular provided deep learning frameworks with their providers
https://towardsdatascience.com/deep-learning-framework-power-scores-2018-23607ddf297a

![alt text](https://cdn-images-1.medium.com/max/1600/1*dYjDEI0mLpsCOySKUuX1VA.png)

## Tensorflow
TensorFlow is the undisputed heavyweight champion. It has the most GitHub activity, Google searches, Medium articles, books on Amazon and ArXiv articles. It also has the most developers using it and is listed in the most online job descriptions. TensorFlow is backed by Google.

## Keras
Keras has an “API designed for human beings, not machines.” It is the second most popular framework in nearly all evaluation areas. Keras sits on top of TensorFlow, Theano, or CNTK. Start with Keras if you are new to deep learning.

## Pytorch

PyTorch is the third most popular overall framework and the second most popular stand-alone framework. It is younger than TensorFlow and has grown rapidly in popularity. It allows customization that TensorFlow does not. It has the backing of Facebook.

## Theano

Theano was developed at the University of Montreal in 2007 and is the oldest significant Python deep learning framework. It has lost much of its popularity and its leader stated that major releases were no longer on the roadmap. However, updates continue to be made. Theano still the fifth highest scoring framework.

# Comparision:

## Criteria 1: Online Job Listings

TensorFlow is the clear winner when it comes to frameworks mentioned in job listings. Learn it if you want a job doing deep learning.

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*kA8dIgRqLdWgKgs2sd7clA.png)

## Criteria 2: Usage


Keras showed a surprising amount of use — nearly as much as TensorFlow. It’s interesting that US employers are overwhelmingly looking for TensorFlow skills, when — at least internationally — Keras is used almost as frequently.

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*6b2Tm0oFr99zKaxkr4g52w.png)
  
  
## Criteria 4: Google Search Activity

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*wpA6C9x_Nri42EzbqnS1fQ.png)

## Criteria 5: Medium Articles

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*Y1cJUgZTC3u_hU1lmdsroQ.png)


## Criteria 6: Amazon Books

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*mtP47q29T6agdkEoJcCw-w.png)

## Criteria 7 : ArXiv Articles

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*7jdNoNkGlx_1EnfevQXRvw.png)
  
## Criteria 8: GitHub Activity

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*eOOYV3C5klsuVBMX31ngxw.png)
  
 --------------------------------
 


  
 








```
# This is formatted as code
```


Before we jump into Tensorflow, we will implemented our first neural network model using Python Numpy package. NumPy is the fundamental package for scientific computing with Python, such as:

1. Linear Algebra
2. Statistics
3. Calculus

## A brief intro to Numpy operations:

1. Creating a Vector:
Here we use Numpy to create a 1-D Array which we then call a vector.





In [0]:
import numpy as np

v1=np.zeros((1,100))
#display(v1)


v2=np.zeros((1,100))
#display(v2)

v2.T.shape

v3=np.ones((1,100))
v4=np.eye(4)
v5=np.random.randn(100,1) # normally distributed random generator with mean 0 and 1 std
v6=np.random.rand(100,1) # uniformally distributed random generator between 0 and 1
display(v4)
display('mean of randn: ',v5.mean())
display('std of randn: ',v5.std())
display('mean of rand: ',v6.mean())
display('min of rand: ',v6.min())
display('max of rand: ',v6.max())

2. Creating a Matrix
We Create a 2-D Array in Numpy and call it a Matrix. It contains 2 rows and 3 columns.

In [29]:
m1=np.zeros((2,3))
display(m1)

matrix=np.array([[1,2,3],[4,5,6]])
display('matrix: ',matrix)
display('matrix shape: ',matrix.shape)

array([[0., 0., 0.],
       [0., 0., 0.]])

'matrix: '

array([[1, 2, 3],
       [4, 5, 6]])

'matrix shape: '

(2, 3)

3. Selecting Elements


In [39]:
display(matrix[0,0]) # first row first column
display(matrix[0,-1]) # first row last column
display(matrix[0,-2]) # first row second last column
display(matrix[0,1:]) # first row and all columns after the first
display(matrix[0,:-1]) # first row and all columns until the last

# Always consider that the left side of : will be included, but the right side not
display(matrix[0,0:2]) # e.g. this will only give the first and second column

1

3

2

array([2, 3])

array([1, 2])

array([1, 2])

4. Describing a Matrix

In [41]:
#View the number of rows and columns
print(matrix.shape)
#View the number of elements (rows*columns)
print(matrix.size)
#View the number of dimensions (2 in this case)
print(matrix.ndim)

(2, 3)
6
2


5. Finding the max and min values

In [62]:
print(matrix)
print(matrix.max())
print(matrix[0,:].max())
print(matrix.min(axis=0)) #Minimum along the first dimension

print(np.min(matrix,axis=0)) #Minimum along the first dimension
print('arg:',np.argmax(matrix,axis=0)) #Argument (index) of the minimum along the first dimension
print('arg:',np.argmax(matrix)) #Argument (index) of the minimum in the matrix

print('MaxIndex:',np.argwhere(matrix == matrix.max()))
print('Indices with values smaller than max:',np.argwhere(matrix < matrix.max()))


testmatrix=np.array([[6,2,3],[4,5,6]])
print(testmatrix.argmax(axis=0))

[[1 2 3]
 [4 5 6]]
6
3
[1 2 3]
[1 2 3]
arg: [1 1 1]
arg: 5
MaxIndex: [[1 2]]
Indices with values smaller than max: [[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]]
[0 1 1]


6. Reshaping Arrays


In [68]:
matrix.shape
matrix2=matrix.reshape((3,2))
matrix.reshape((1,6))
matrix.reshape((1,2,3)) #dim 0 size is 1, dim 1 is 2, dim 2 is 3
matrix.reshape((1,-1,3)).shape #Calculate the size of one dimension automatically

(1, 2, 3)

7. Calculating Dot Products

In [70]:
vector_1=np.array([1,2,3])
vector_2=np.array([4,5,6])

#Calculate the dot product
print(np.dot(vector_1,vector_2))
#Alternatively you can use @ to calculate dot products
print(vector_1@vector_2)


matrix2.dot(matrix)

32
32


array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

##Linear regression in Numpy:

---



Write the numpy code for the following model:

$Y=WX+B$

where $X$ is 3x10 matrix:  10 samples and 3 features

$Y$ is 4x10 matrix: 10 samples and 4 outputs

$W$ is the weights matrix with the shape 4x3: connecting 3 inputs to 4 outputs

$b$ is a vector with a size 4 ( one bias per output)


In [76]:
#Inputs or features matrix
X=np.random.rand(3,10)
display('shape of X:',X.shape)

#Weights matrix
W=np.random.rand(4,3)

#bias
b=np.zeros((4,)) # This is a vector
b=np.zeros((4,1)) # This is a matrix

#regression model
Y=np.dot(W,X)+b  # 4x3 , 3x10

display('Y: ',Y.shape)


'shape of X:'

(3, 10)

'Y: '

(4, 10)

## One neuron model in numpy:

A single neuron has multiple inputs and one output, in addition to the linear regression model, we need to add non linearity through an activation function:

$Y= f(WX+B)$

where $X$ is n x m matrix:  m samples and n features/inputs

$f(g)= \frac{1}{1+\exp(-g)}$  is a sigmoid acitavation function

$Y$ is nh1 x m matrix: m samples and ny outputs

$W$ is the weights matrix with the shape nh1 x n: connecting 3 inputs to 4 outputs

$b$ is a vector with a size nh1 ( one bias per output)





In [0]:
#Function definition with def
def f(x):
  return 1.0/(1.0 + np.exp(-x))


num_inputs=3
num_outputs=1
num_samples=100

#Function definition with lambda
f=lambda x: 1.0/(1.0 + np.exp(-x)) # activation function (use sigmoid function)

#Inputs or features matrix
X=np.random.rand(num_inputs,num_samples)

#Weights matrix
W=np.random.rand(num_outputs,num_inputs)

#bias
b=np.random.rand(num_outputs,1)

#regression model
Y=f(np.dot(W,X)+b)
display(Y)
display(Y.shape)

## One hidden layer model in numpy:

The difference from the one neuron model is simple:  we need only to change the number of output "ny"

In [87]:


num_inputs=3
num_outputs=3
hidden_layer_1_outputs=4
hidden_layer_2_outputs=3
num_samples=100

#Function definition with lambda
f=lambda x: 1.0/(1.0 + np.exp(-x)) # activation function (use sigmoid function)

#Inputs or features matrix
X=np.random.rand(num_inputs,num_samples)

#Weights matrix of the first hidden layer
W_h1=np.random.rand(hidden_layer_1_outputs,num_inputs)
#Weights matrix of second hidden layer
W_h2=np.random.rand(hidden_layer_2_outputs,hidden_layer_1_outputs)

#bias
b_h1=np.random.rand(hidden_layer_1_outputs,1)
b_h2=np.random.rand(hidden_layer_2_outputs,1)

# Calculate output of hidden layer 1
h1=f(np.dot(W_h1,X)+b_h1)
display(h1.shape)
# Calculate output of hidden layer 2
h2=f(np.dot(W_h2,h1)+b_h2)

display(h2)
display(h2.shape)

(4, 100)

array([[0.88026115, 0.88548133, 0.85749299, 0.87521716, 0.8856078 ,
        0.85687625, 0.85523738, 0.87936421, 0.85271286, 0.87647476,
        0.85022721, 0.87622287, 0.88325717, 0.87091168, 0.88326437,
        0.88268474, 0.84454478, 0.88148087, 0.88157402, 0.87489153,
        0.87382521, 0.87905573, 0.85776867, 0.86913832, 0.88662339,
        0.8854361 , 0.88859656, 0.85982988, 0.86295813, 0.86506719,
        0.87718931, 0.87066716, 0.86479666, 0.8730098 , 0.85939554,
        0.87640508, 0.86081737, 0.89270766, 0.86638225, 0.86450709,
        0.85541204, 0.86315426, 0.87508522, 0.87643541, 0.89085746,
        0.8823115 , 0.88338279, 0.87222344, 0.88574952, 0.86624576,
        0.87325252, 0.87998843, 0.88232773, 0.87846912, 0.86762619,
        0.88623347, 0.87805117, 0.8871683 , 0.85550569, 0.86027217,
        0.85435645, 0.89189576, 0.88941386, 0.86845774, 0.8339384 ,
        0.87668765, 0.89343134, 0.86377169, 0.8651168 , 0.87789629,
        0.88451292, 0.8799735 , 0.86862863, 0.85

(3, 100)

## Gradient descent in Numpy:
Let us now start training a neural network
We start by implementing a simple gradient descent for linear regression

# Test 1

##Assignment 1
### Backpropagation in Numpy:
